### ISSUE TITLE
[MU4 Issue] Crashes when loading Arcadia Grand Piano VST

### ISSUE THREAD

**Issue by Nazgul37** [musescore/MuseScore#11094]
**Describe the bug**
When loading the VST [Arcadia Grand Piano](https://organicinstruments.thejonathanv.com/products/arcadia/) by Organic Instruments, MuseScore will crash. 

**To Reproduce**
1. Install [Arcadia Grand Piano](https://organicinstruments.thejonathanv.com/products/arcadia/), by Organic Instruments
2. Open MuseScore, create a blank score with a piano stave. 
3. Open the mixer and set the piano sound to VST > Arcadia
4. MuseScore attempts to load the plug-in and crashes.

**Expected behavior**
The plug-in should load and open as it does in any other music production or notation software. 

**Platform information**
 - OS: Windows, MacOS

**Comment by boryskuzmenko** [comment]
@Nazgul37 Thanks for the logging this issue

**Comment by Tantacrul** [comment]
@Nazgul37 - there has been a lot of work done on VST recently. Could you possibly download the latest nightly and test this again?

https://ftp.osuosl.org/pub/musescore-nightlies/

**Comment by Nazgul37** [comment]
Hi @Tantacrul , Arcadia still crashes MuseScore when it's loaded, even in the latest nightly. Also because the plug-in can take a moment to initialize, it looks like it causes Musescore to be slow to open as well (is it scanning VSTs on launch?) Let me know if there's anything you need, since I'm actually the dev behind Arcadia and Organic Instruments.

**Comment by cbjeukendrup** [comment]
Indeed, MuseScore scans plugins on every launch. The plan is to change that: #11412

**Comment by Tantacrul** [comment]
> Let me know if there's anything you need, since I'm actually the dev behind Arcadia and Organic Instruments.

@Nazgul37  That would possibly be very useful for us. Especially if we can ask you technical questions about the plugin / anything about it that would differentiate it from others, etc.

What would also be great is if we could have a trial / demo version for testing purposes. This is generally how we fix these issues. (Which makes it a pain because we have to keep buying plugins!)

**Comment by Tantacrul** [comment]
Incidentally @Nazgul37, an email you can use to contact me is info.tantacrul@gmail.com

**Comment by DmitryArefiev** [comment]
@Nazgul37 Can you try again in latest master please? Does it still crash?

Thanks!

**Comment by Nazgul37** [comment]
Hi @DmitryArefiev, I just downloaded the latest Musescore Nightly (20.10.2022). The plug-in still crashes Musescore. For some reason it appears that the main plug-in UI interface is getting shown before all the samples are finished loading? Then when the loading actually finishes, Musescore crashes.

**Comment by DmitryArefiev** [comment]
> Hi @DmitryArefiev, I just downloaded the latest Musescore Nightly (20.10.2022). The plug-in still crashes Musescore. For some reason it appears that the main plug-in UI interface is getting shown before all the samples are finished loading? Then when the loading actually finishes, Musescore crashes.

Got it. Thanks!

**Comment by Nazgul37** [comment]
Is there any update to this one? It's been over a year now, with the crash occurring in production MuseScore 4...

**Comment by abariska** [comment]
@Nazgul37 your VSTi is not really famous and priority of the crash can't be high. To process this crash faster you could provide a 2-3 licenses for our development team

**Comment by Nazgul37** [comment]
Thanks @abariska , while it might not be a blockbuster brand, it's quite popular among the education market and schools (groups that also primarily use MuseScore 😉). I'd also like to ensure that the issue is resolved before our new plugins in the pipeline get released. 

I've already provided a number of licenses to your developers. If more are still required, could you please direct me to where they should be distributed, or how I can assist with moving this along?

**Comment by DmitryArefiev** [comment]
FYI @bkunda

**Comment by Tantacrul** [comment]
@Nazgul37 - hey there.

Although I did get the plugin when you first raised this issue, no one else on our team has it. If I recall, we also need to set up iLok accounts too, correct?

In order to have this handled by us, we'd need a few licenses (probably 3) so our dev team and testing team can all do their part. You can email me back on our old thread and I'll add @bkunda, who can take it from there.

**Comment by bkunda** [comment]
@Nazgul37 yesterday we merged a fix that _might_ fix this issue, but will need your help to see if it worked. 
Could you please re-test using the latest nightly? Many thanks!

**Comment by zacjansheski** [comment]
Closing, no response

**Comment by Nazgul37** [comment]
@bkunda I've tested with MuseScore 4.4.1.242500503 Nightly. The issue still persists.

**Comment by CubikingChill** [comment]
Is the issue still there?

**Comment by CubikingChill** [comment]
@Nazgul37 You may want to have a look at #16144 
This is a paid VST so unfortunately I cannot test it myself.

**Comment by bkunda** [comment]
We now have a new PR that ports @CubikingChill's fix and adds further fixes. It would be great if this issue could please be retested using this build: https://github.com/musescore/MuseScore/pull/33086

Many thanks!

**Comment by CubikingChill** [comment]
I installed arcadia grand piano. The .vst3 is in the right folder. But it seems I cannot find it inside Musescore UI. I checked debug log but cannot get anything useful. Can anyone look into it?

**Comment by DmitryArefiev** [comment]
@CubikingChill Have you activated license/trial license for Arcadia? If yes, try to Factory reset

Arcadia is detected fine (with trial license) in **MSS4.7.4 (Win10)** on my side. But still crashes

https://github.com/user-attachments/assets/a7bdd26f-f486-4a89-a00e-1b8f42871247
