### ISSUE TITLE
[MU4 Issue] Audio Playback for MOTU M4 Audio Interface is distorted

### ISSUE THREAD

**Issue by NinjaNas** [musescore/MuseScore#11190]
**Describe the bug**
The playback for MuseScore 4 sounds normal when running with my headphones directly connected to my PC. However, while using my MOTU M4, the playback sounds distorted and rings. The tempo is drastically slowed down and every note has a long decay. This issue is reproduced with all sample rates. I have tried using other VST3s and the same issue has occurred. Also, the playback for sfz has a weird staccato effect to it which continues into other dynamic changes. 

**Platform information**
 - OS: Windows

**Additional context**
MuseScore 4 version from first alpha post 
Settings used for videos below:
![image](https://user-images.githubusercontent.com/54213302/163260590-d27478a6-a9b1-4609-846a-9b7593ffb6d9.png)

https://user-images.githubusercontent.com/54213302/163259008-afe6b321-1eb2-4a21-bfe9-b1932cc79c41.mp4

https://user-images.githubusercontent.com/54213302/163259012-a6d4d58b-f4f5-4efe-b693-f428cd31ebb2.mp4

**Comment by DmitryArefiev** [comment]
Hi @NinjaNas , have you seen the same issues using MOTU M4 in another DAWs or Notation software?

BTW Did you try MOTU M4 in MuseScore3?

**Comment by NinjaNas** [comment]
@DmitryArefiev I have no issue using my MOTU M4 on MS3, Sibelius, or Ableton Live 10 on any API or setting. I have also tested the Focusrite Scarlett Solo on the MS4 alpha build and it works as intended while the MOTU M4 has the issue shown above. I can reproduce the issue on all scores.

**Comment by Tantacrul** [comment]
@DmitryArefiev This is one to test once we implement 'Devices'. It's possible it is already fixed. I'm aware there are a few of these issues which all seem related. In particular, I note the 48K sample rate 😄 .

**Comment by NinjaNas** [comment]
@Tantacrul I have downloaded the latest nightly build 2022-06-20 04:26 and the issue is still present. 
![image](https://user-images.githubusercontent.com/54213302/174660028-cd930215-dcbb-46c1-9e09-dbad4ac52807.png)
I was able to reproduce the issue for all of the sample rates above.
If you need any more info please do ask.

**Comment by cbjeukendrup** [comment]
Maybe also related: #11222

**Comment by DmitryArefiev** [comment]
Hi @NinjaNas can you check this build please - https://github.com/musescore/MuseScore/actions/runs/2594689300

It's a little bit raw build but it has sample rate change. Just check please how switching between sample rates in Preferences>I/O affects playback quality.

One notice - MU will be crashing after restarting. Use Factory reset to fix it. 
Just try one time if that build can fix you problem with MOTU and after you can easily return to master builds.

Thanks!

**Comment by NinjaNas** [comment]
I did some testing on the build @DmitryArefiev. 

It seems to me that my MOTU software is not tied to MS4. In Ableton, when I change the sample rate it changes accordingly in the MOTU software. 

At the sample size of 48000, the playback is correct. I didn't show this in the video but it works for all buffer sizes without issue.

However, 44100, 88200, and 96000 all change the pitch of the notes in playback with 44100 being the lowest in pitch and 96000 the highest.

The choppiness in the playback is still present in 88200 and 96000 which is not fixed unless the buffer rate is high enough. 44100 and 48000 show no issue of choppiness.

Also the scrollbar in the buffer size dropdown menu should be visible during hover or shown by default. I did not know for some time while testing that the menu was scrollable. 

https://user-images.githubusercontent.com/54213302/176953279-d01eb0b6-eef7-449b-b7f2-f19c6af9a0ff.mp4

**Comment by NinjaNas** [comment]
@DmitryArefiev Just checking if you have seen my comment.

**Comment by DmitryArefiev** [comment]
> @DmitryArefiev Just checking if you have seen my comment.

@NinjaNas Oh sorry! I saw the notification about your previous comment but just forgot to reply..

Thank you for investigation. For now we removed sample rate settings because of technical issues. 
But can you try again on master build to see if distortion still occurs with your MOTU interface? 

(if distortion still there please try to Reset factory settings and change sample rates in MOTU control panel) 

Thanks!

**Comment by NinjaNas** [comment]
@DmitryArefiev After more testing, I figured out that the issue is about the Windows sample rate and not about the interface itself.

If you set your Speakers Realtek Audio to a high sample rate (176400Hz or 192000Hz) the distortion will occur. 
Anything 96000Hz and below work just fine, however the pitch shift is still an issue.

Also I can use 96000Hz at 256 buffer size just fine, however, for 176400Hz or 192000Hz distortion is still an issue even at 4096 buffer size.

**Comment by DmitryArefiev** [comment]
@NinjaNas  Strange.. I have a doubts that Speakers Realtek Audio  supports 176400Hz or 192000Hz and it can be expected for Realtek Audio to have distortion on that sample rates. But you hear distortion in MOTU outputs, right?

Regarding pitch change issue it can be the same as #10804

> Also I can use 96000Hz at 256 buffer size just fine,

So, the workaround you described is fixing your issue (in master build) ?

**Comment by NinjaNas** [comment]
> @NinjaNas Strange.. I have a doubts that Speakers Realtek Audio supports 176400Hz or 192000Hz and it can be expected for Realtek Audio to have distortion on that sample rates. But you hear distortion in MOTU outputs, right?

@DmitryArefiev Yes, there is still distortion from MOTU at 176400Hz or 192000Hz.
My Speakers Realtek Audio goes up to 192000Hz.

![image](https://user-images.githubusercontent.com/54213302/180294234-24fdef8a-2184-47bf-bd50-3850315750fc.png)

> So, the workaround you described is fixing your issue (in master build) ?

Yes, anything 96000Hz and below works fine on MOTU output.

**Comment by DmitryArefiev** [comment]
@NinjaNas Thanks for investigation! It's good you find a solution to solve the problem but still strange that changing sample rate settings for Realtek Audio also affects MOTU outputs..

One more attempt.. Can you try the build from here https://github.com/musescore/MuseScore/actions/runs/2602243717 when you have time?

Thanks!

**Comment by NinjaNas** [comment]
@DmitryArefiev 
> One more attempt.. Can you try the build from here https://github.com/musescore/MuseScore/actions/runs/2602243717 when you have time?

I believe #10804 is fixed in this build. I hear no difference in pitch between sample rates even at 176400Hz and 192000Hz 

> It's good you find a solution to solve the problem but still strange that changing sample rate settings for Realtek Audio also affects MOTU outputs.

To clarify, I tested both outputs separately. Both had the same issue of distortion when the sample rate was higher than 96000Hz. 

I should mention that playback is slowed-down also. This could be related to #12483, however, the max duration I got while testing (I used the same score as they did) on MOTU outputs was 4-6 seconds compared to their 8 seconds. It was even faster on Realtek.

Their playback pitch is definitely higher than normal and I believe that they may be on a different sample rate.

**Comment by DmitryArefiev** [comment]
@NinjaNas Thanks for testing! 

> To clarify, I tested both outputs separately. Both had the same issue of distortion when the sample rate was higher than 96000Hz

So do you have distortion only on 176400Hz and 192000Hz with Realtek and with MOTU as well in MuseScore?

And how Realtek and MOTU beahave when just playing a music (YouTube) or working in DAW (Ableton) on 176400Hz and 192000Hz?

.

**Comment by NinjaNas** [comment]
@DmitryArefiev They both work as expected on Youtube and Ableton. In fact, they both work in MS3 as well. It seems to only be an issue in MS4.

**Comment by DmitryArefiev** [comment]
> @DmitryArefiev They both work as expected on Youtube and Ableton. In fact, they both work in MS3 as well. It seems to only be an issue in MS4.

@NinjaNas Got it. Thanks!

**Comment by Tantacrul** [comment]
@NinjaNas - thanks so much for all your investigation so far. Can you confirm 2 things:

1. Is the issue still present
2. You've mentioned earlier in the thread (if I understood correctly) that there were some settings you could change on Windows that resulted in MS4's playback working. Is that correct?

**Comment by Tantacrul** [comment]
Moving to post beta for now.

**Comment by NinjaNas** [comment]
> Is the issue still present
@Tantacrul Thanks for checking in. The distortion issue has changed from playing too slow to now too fast. For me #10804 is not fixed in the current master as well.

> You've mentioned earlier in the thread (if I understood correctly) that there were some settings you could change on Windows that resulted in MS4's playback working. Is that correct?

There is no need to change setting on Windows because MuseScore now read the sample rate directly from the audio device. The solution is to turn the sample rate down to 44k or 48k. Anything above that will get a distortion effect.

 

https://user-images.githubusercontent.com/54213302/195361586-c1427121-34d5-4e83-849f-e4300f7a066a.mp4
