### ISSUE TITLE
Playback incorrectly starts at the end of a selection

### ISSUE THREAD

**Issue by Majora320** [musescore/MuseScore#11493]
Playback starts at the end of a selection.

To replicate the bug you need to: 

1. Place 4 quarter notes in a measure
2. Hold shift and click on the first quarter note (on the left)
3. Continue holding shift, then click on the last note in the measure (on the right)
4. Press play
5. Playhead starts from the last selected note on the right

https://user-images.githubusercontent.com/16787503/166164676-d9957dfe-42f4-49ac-bb2e-4f9910cfb63e.mp4

Expected:
Playback **always** starts at the beginning of a range (or list) selection

**Comment by Tantacrul** [comment]
I just tried this on the latest nightly and can't replicate the issue. When I select a measure, playback always starts at the start. Have you downloaded the latest build and tried it there?

**Comment by Majora320** [comment]
Yes, this is on the latest build. I think my video was a little ambiguous, sorry about that. I'm selecting a range of notes with shift-click here, not selecting the measure by clicking on it. Playback works as normal if I select the measure.

**Comment by Tantacrul** [comment]
Confirmed. To replicate the bug you need to: 

1. Place 4 quarter notes in a measure
2. Hold shift and click on the first quarter note (on the left)
3. Continue holding shift, then click on the last note in the measure (on the right)
4. Press play
5. Playhead starts from the last selected note

**Comment by cbjeukendrup** [comment]
@Majora320 @Tantacrul This should be fixed with PR #11322. Could you confirm this?

**Comment by Majora320** [comment]
No, that doesn't fix it, unless there's been some changes since this bug was logged that didn't show up. In the original bug I noted that I tested with that PR, but  it looks like that got left out when my message was edited.

**Comment by MarcSabatella** [comment]
Perhaps obvious, I would assume it’s order-dependent.  That when creating a range selection by click of one note followed by shift+click of another, it matters whether you start on the left or the right - last note clicked wins.

**Comment by Tantacrul** [comment]
'Last click wins' was what I noticed in the original issue too.

**Comment by cbjeukendrup** [comment]
I'm pretty sure that (the latest version of) PR #11322 fixes this issue; on the master branch I can reproduce it but with that PR I can't. @DmitryArefiev could you please check it?

**Comment by DmitryArefiev** [comment]
> I'm pretty sure that (the latest version of) PR #11322 fixes this issue; on the master branch I can reproduce it but with that PR I can't. @DmitryArefiev could you please check it?

@cbjeukendrup Yes, I tested this in build from #11322 on Windows - the main issue also **doesn't reproduce** on my
 side

(and I can reproduce in master)

**Comment by cbjeukendrup** [comment]
Thanks for checking! I've marked the PR as a fix for this issue.

**Comment by zacjansheski** [comment]
I have reproduced this issue, in current master but only directly after opening a score

https://github.com/musescore/MuseScore/assets/69917893/03a0b04a-7171-49e8-a8ca-0e932dde8b93

FYI @Eism
