### ISSUE TITLE
[MU4 Issue] Inconsistent scrollbar in pallettes

### ISSUE THREAD

**Issue by jessjwilliamson** [musescore/MuseScore#11528]
**Describe the bug**
A strange scrollbar bug when scrolling through 'Bagpipe embellishments' in palettes. This specific category has the longest vertical list which causes strange scrollbar behaviour.
So far only tested using a mouse wheel, unsure about the trackpad yet.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to pallettes
2. Click on 'Bagpipe embellishments' and expand the category
3. Scroll down through palettes
4. See bug

**Expected behaviour**
A consistent scrollbar throughout the whole vertical palettes section.

**Screenshots**

https://user-images.githubusercontent.com/71656189/166907822-b8742e4a-7a79-44bd-b392-a46105d3407a.mp4

**Comment by llui85** [comment]
Additional context from https://github.com/musescore/MuseScore/issues/10085#issuecomment-1007350771:

> Comment by **cbjeukendrup**:
> 
> Palettes have an additional problem. They make use of the QML ListView component. That component only loads the list items that are currently in the viewable area; items that are scrolled out of view are destroyed (to save memory) and will be recreated when they will get into the view again.
> 
> Because not all items are loaded at a time, the total height of the scrollable area cannot be calculated. It can only be estimated, which is what QML does: it takes the average height of all visible items, and then uses that height to estimate the total height.
>
> This works perfectly fine if all list items have exactly the same height, which is the case in most list views. But in the Palettes, this is totally different: collapsed palettes are very small, while expanded palettes vary from tall to very tall. The estimated total height will be totally wrong. Also, it will change continuously while scrolling, because other items become visible, so the average height of the visible items changes. That causes jumping and other strange behaviour.
> 
> I'm not totally sure about a solution. One option would be to replace the ListView by a Flickable+Column+Repeater. I also believe that you can control the "cache size" of the ListView, so if that works, that would be another option.

**Comment by FrancRos31** [comment]
Fixed in version 4.5.2, Windows 10 Pro, mouse wheel.

https://github.com/user-attachments/assets/2858b0f4-1901-4a46-9350-3474453054a7

**Comment by cbjeukendrup** [comment]
Hm... even when expanding many different palettes with many different heights? Still reproducible on macOS. 
Maybe the update to Qt 6.2.11 fixed it (that was applied on Windows only), which would be good news, but let's make really sure that it's really fixed.

**Comment by FrancRos31** [comment]
The scroll bar on the DevTools 'Settings' page is affected too.

https://github.com/user-attachments/assets/1541f3d1-c95c-4e51-b94e-e2baf0fa83ce

OS: Windows 10 Version 22H2 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.6.0-252070328, revision: github-musescore-musescore-0781b82
