### ISSUE TITLE
[MU4 Issue] Master palette elements cannot be added via drag & drop

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#11580]
It seems that elements from the Master Palette - including the Symbols section, which is really the only section which we actually *need* a master palette - cannot be added to the score via drag & drop.  You can initialize the drag operation, but the "no drops allowed" icon never changes to the "drop here" icon as you hover elements in your score that should allow it.

1) new score
2) open View / Master Palette
3) try to drag a clef to the initial measure or the initial clef; or try to drag anything from the Symbols section to the first rest

Result: you never reach a point where you can drop

Adding by click works normally; just drag & drop fails.

**Comment by Tantacrul** [comment]
@MarcSabatella - I can drag items on the score on Mac (latest nightly.) Is it a Windows/Linux thing or both?

**Comment by MarcSabatella** [comment]
Linux at least.  I'll try to test Windows later.  Here's a GIF.  To be clear: only the master palette has this issue, not the standard palette.

![image](https://user-images.githubusercontent.com/1799936/168592043-b48bf092-76ed-41ac-be2f-b42009779da9.png)

**Comment by MarcSabatella** [comment]
![Recording 2022-05-16 at 06 25 13](https://user-images.githubusercontent.com/1799936/168592553-c93595a3-f919-4488-ba6d-82e920d98cf9.gif)

**Comment by MarcSabatella** [comment]
Works for on my Windows system.  Would be good to hear from another Linux user.  Could be a matter of different distributions or window managers or whatever.  I'm on Debian but running as a container within ChromeOS.  That *almost* never matters - issues I see on this system are almost always reproducible on other systems - but there have been two or three problems over the years that turned out to be unique to running under ChromeOS, and one of them had to do with drag & drop.

**Comment by Tantacrul** [comment]
@DmitryArefiev - can you check?

**Comment by DmitryArefiev** [comment]
@Tantacrul @MarcSabatella I've tested this on Linux Mint 20.2 and Win10/Mac12 - **all works fine for me** (latest master)

@boryskuzmenko I know you have Ubuntu. Can you try on your side please?

**Comment by Tantacrul** [comment]
@MarcSabatella is running a slightly different setup, which (if I understand correctly) is a modified Chromebook?

With that in mind, it seems like a rather niche problem for a very niche setup.

**Comment by DmitryArefiev** [comment]
@Tantacrul Let's set the low priority then (p4) and move to beta2 ?

**Comment by Tantacrul** [comment]
Done

**Comment by MarcSabatella** [comment]
Definitely still not working for me, but thanks for confirming it doesn't affect all systems or even all Linux systems!

FWIW, it's not a "modified" Chromebook, but a standard one running Linux the standard way as supported by Google.  This configuration might not be the most common, but it's one that tons of music teachers and students use, because Chromebooks pretty much completely dominate the US education market.  So it's not really a niche configuration, but one we definitely want to support in general.

On the other hand, if the worst that happens is that drag and drop from the master palette doesn't work but the normally click method does, this particular issue is not a very high priority regardless of how common this configuration is.

**Comment by Tantacrul** [comment]
Noted about the Chromebooks. Thanks.

**Comment by Wasabichicken** [comment]
I guess I'll add that I'm still seeing this in newer Musescore versions on a fairly recent Debian.

OS: Debian GNU/Linux 12 (bookworm), Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.3-242971445, revision: github-musescore-musescore-eb6b367. QT version 6.2.4. Window manager: Sway 1.7-6 (Debian package).
