### ISSUE TITLE
[MU4 Issue] Secondary sixteenth note beams not displayed for eighth + 2 sixteenths

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#11658]
The secondary beam for sixteenth notes is not getting rendered in ascending patterns involving an eighth and two sixteenth.  In the following example, the second a third notes are sixteenth - you can tell this because of the spacing, also you can see the the weird extended stem sticking out past the eighth note beam.  But the secondary beam actually identifying these as sixteenth is missing:

![image](https://user-images.githubusercontent.com/1799936/168719301-3913453a-836b-4a7f-ae4e-d81a8a854cdd.png)

In the second beat, it's the same rhythmic pattern, but this time descending.  That seems to be the differentiator here.  Oh, also - seems to only happen if downstem.

This is tested in a build from May 16, on Linux.  Pretty sure it was working not so long ago?  Hard to imagine this would have been not noticed if it had been broken long, although I'm also surprised vtests didn't catch whatever broke it.

**Comment by oktophonie** [comment]
I can reproduce this (in Windows) with the nightly from 16 May but it seems fixed as of 17 May.

**Comment by MarcSabatella** [comment]
Hmm, I can still reproduce this in the most recent nightly on Linux.  Same example as shown above: treble clef staff, eighth note C5, sixteenth notes D6 & E6.  I don't see any changes made in the past 24 hours that would explain this having been fixed?

**Comment by MarcSabatella** [comment]
No, this one affects all scores, even pre-existing ones.

**Comment by oktophonie** [comment]
As far as I can tell this is fixed by (or not broken in!) #11608 which is awaiting merging.

**Comment by SnyBr** [comment]
If it helps, I first noticed this happening after cross-staff beaming was merged.
