### ISSUE TITLE
[MU4 Issue] Crash on changing workspace via bottom toolbar

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#12868]
**Describe the bug**
MuseScore crashes when changing workspaces via the bottom toolbar

**To Reproduce**
1. Create a new workspace using bottom toolbar
2. Now switch back to the default, also using the bottom toolbar

**Result**
MuseScore crashes.

**Expected behavior**
MuseScore should change to the selected workspace.

**Platform information**
 - OS: tested on Linux and Windows.  On Linux, the crash is instant; on Windows, it hangs a minute first.

**Additional context**
The initial change when you create the workspace works; only changing to an already-existing workspace fails.  Workaround - use the the View menu to change workspaces - that doesn't crash.  So the problem seems to be in the dialog code more than the workspace code itself.

**Comment by RomanPudashkin** [comment]
@MarcSabatella Looks like this crash has already been fixed here: https://github.com/musescore/MuseScore/pull/12556

Where did you get the build? If you build the app yourself, make sure this option is disabled:
<img width="449" alt="Screenshot 2022-08-22 at 19 02 03" src="https://user-images.githubusercontent.com/67867444/185967012-cd12b8b3-2ebb-4c87-8944-0962891721f0.png">

I can only reproduce it if the option is enabled

**Comment by RomanPudashkin** [comment]
Let's close this issue as we cannot reproduce it anymore (neither on windows nor on linux). Feel free to reopen it if you can reproduce it

**Comment by MarcSabatella** [comment]
Still reproducible for me on both Linux and Windows, current nightly.

Here's video:

![image](https://user-images.githubusercontent.com/1799936/190251596-31a46f5a-a97e-4bdb-9e49-af8046fead82.png)
