### ISSUE TITLE
[MU4 Issue] MuseSounds is not being recognised by MuseScore

### ISSUE THREAD

**Issue by Mark-WWW** [musescore/MuseScore#13934]
**Describe the bug**
MuseSounds not showing up on MS4 Beta

**To Reproduce**
I've installed the newly released of MS4 and it appears to be working just fine, except that I am unable to select MuseSounds at all - it just doesn't appear in the Mixer where it ought to. If I look under View|Playback Setup it says MuseScore Basic is Active and Muse Sounds is Inactive, but clicking on MuseSounds doesn't change anything.

I've downloaded all the MuseSounds sections from MuseHub and they are all showing as ticked (and 13.5GB of data is on my hard drive in C:\ProgramData\MuseHub\Downloads), but MuseSounds just doesn't want to appear in the program on my system.

**Expected behavior**
I'd expect MuseSounds to appear in the Mixer under Sound but it does not appear.
![Clipboard01](https://user-images.githubusercontent.com/111195078/197408889-46b2a39f-b8b3-44de-950a-27d76121c2e8.png)
![Clipboard02](https://user-images.githubusercontent.com/111195078/197408913-7e592e9d-dc4a-4483-99f1-cf5b45ab1c3a.png)
![Clipboard03](https://user-images.githubusercontent.com/111195078/197409064-9d384727-7ca7-4a54-84e7-9dfe37c86911.png)

**Screenshots**

**Platform information**
 - OS: Windows 10

**Additional context**
I tried uninstalling MS4 and then re-installing again from MuseHub, but it made no difference - I'm still unable to make MuseSounds active.

**Comment by eakwarren** [comment]
Same behavior for me on MacOS Monterey 12.6. I also had a couple nightly builds installed beforehand.

I deleted Muse Hub and MuseScore 4 apps and deleted the MuseSounds from the custom place I specified in the settings panel of MH. I also deleted ~/Library/Application Support/MuseScore/MuseScore4/.

Re-downloaded MH, installed MS 4. Installed all the Muse Sounds again in MH. Started MS4 and loaded a new Orchestral - Symphony Orchestra template. Still unable to select Muse Sounds in Playback Setup, same as the last screenshot Mark-WWW posted above.

One thing I noted was MH kept my custom Setting-Sounds Install Location on the re-install of MH. I couldn't find any other Preference files, so not sure where that setting is cached and if that is contributing to the issue.

**Comment by Tantacrul** [comment]
@eakwarren and @Mark-WWW - did you install MuseScore using the hub application? This is necessary in order for Muse Sounds to work.

If not, then uninstall any version of MS4 you have on your machine and then install via the hub. If the issue persists, let us know. This is the most common point of confusion at the moment

**Comment by eakwarren** [comment]
@Tantacrul, Yes MS4 was installed from MH on the Settings cog wheel both times.

**Comment by Mark-WWW** [comment]
AwesomeTyper Many thanks for your suggestion in https://github.com/musescore/MuseScore/issues/13952. It has solved the problem for me, and I am now able to hear MuseSounds in all its glory. Yippee!

Hard to know why deleting the MuseHub folder from %ProgramData% is necessary and just deleting and re-installing MuseHub and MS4 wasn't sufficient, but that was the case for me too.

Thanks again.

**Comment by AwsomeTyper** [comment]
> AwesomeTyper Many thanks for your suggestion in #13952. It has solved the problem for me, and I am now able to hear MuseSounds in all its glory. Yippee!
> 
> Hard to know why deleting the MuseHub folder from %ProgramData% is necessary and just deleting and re-installing MuseHub and MS4 wasn't sufficient, but that was the case for me too.
> 
> Thanks again.

Glad I was able to help! I will work on replicating this issue and finding a better workaround this afternoon.

**Comment by philipplndwhr** [comment]
> Same behavior for me on MacOS Monterey 12.6. I also had a couple nightly builds installed beforehand.
> 
> I deleted Muse Hub and MuseScore 4 apps and deleted the MuseSounds from the custom place I specified in the settings panel of MH. I also deleted ~/Library/Application Support/MuseScore/MuseScore4/.
> 
> Re-downloaded MH, installed MS 4. Installed all the Muse Sounds again in MH. Started MS4 and loaded a new Orchestral - Symphony Orchestra template. Still unable to select Muse Sounds in Playback Setup, same as the last screenshot Mark-WWW posted above.
> 
> One thing I noted was MH kept my custom Setting-Sounds Install Location on the re-install of MH. I couldn't find any other Preference files, so not sure where that setting is cached and if that is contributing to the issue.

Similar problem on MacOs 12.5.1, I installed Musescore through MuseHub, I tried downloading the fonts through MuseHub. Musescore's  sound font directory was not equal to the directory MuseHub saved the fonts to. Changing MuseScore's sound font directory did not result in the sound fonts being selectable. 

I have not tried deleting the directory, the MuseHub App and Musescore yet.

**Comment by iamtesch** [comment]
Thanks for the reports here; we are working to debug these issues.

A note of clarification -- the Muse Sounds go through a slightly different pipeline than the built-in sound fonts, and therefore the sound font folder should not be changed to the Muse Sounds folder.

**Comment by DEHWall** [comment]
Same problem here on Windows 10 / 11 Insider Release 22623.870, but resolved after following AwesomeTyper's suggestion in https://github.com/musescore/MuseScore/issues/13952 (many thanks)  - In addition removed all musescore 4 files from Appdata\Local and \roaming folders.
I believe it happened after applying the Check for Updates option which installed 4.0.27 (subsequently uninstalled)

**Comment by telephono** [comment]
Same Problem on macOS 13.0 (Apple M1)
MuseScore 4.0.0 installed through MuseHub but MuseSounds are greyed out in View -> Playback Setup

**Comment by cesarizu** [comment]
I have a similar issue running Musescore nightly on openSUSE linux. Is there any way I can help troubleshoot this problem?

**Comment by vttphm** [comment]
I still have the issue on a 12.5 M1 Mac; can the Windows trick be replicated here?

**Comment by Fince10086** [comment]
> MuseScore 4.0.0 installed through MuseHub but MuseSounds are greyed out in View -> Playback Setup

Same issue too in macOS 13.0 with M1 Pro

**Comment by Tantacrul** [comment]
@Fince10086 @vttphm - Can you both do the following if you haven't done it already?

1. Uninstall the helper by right-clicking on the Muse Hub logo (top left) and selecting 'Uninstall helper'
2. Uninstall MS4 and the Muse Hub
3. Go to https://www.musehub.com/ and use it to install the Muse Hub again
4. Use the Muse Hub to install MS4 and any updates that are offered to sounds or the Muse Hub itself

**Comment by telephono** [comment]
@Tantacrul 
<img width="1080" alt="Screenshot 2022-11-10 at 17 31 54" src="https://user-images.githubusercontent.com/111712/201153006-ecf78d21-6f9b-4adc-8454-50ded274e098.png">

No luck!
I did uninstall the helper, Uninstalled (deleted from Applications Folder) MuseHub and MuseScore and installed MuseHub again. Installed MuseScore through MuseHub. The previously installed SoundFonts were already recognised in MuseHub. No install or update neccessary...

**Comment by Tantacrul** [comment]
> Uninstall the helper by right-clicking on the Muse Hub logo (top left) and selecting 'Uninstall helper'
Uninstall MS4 and the Muse Hub
Delete ~/Library/Containers/com.muse.hub
Go to https://www.musehub.com/ and use it to install the Muse Hub again
Use the Muse Hub to install MS4 and any updates that are offered to sounds or the Muse Hub itself

@iamtesch - wonder if this is useful to you ^

An extra step to get it working on MacOS.

**Comment by taylank** [comment]
Recently ran into this problem. Fixed it by following these steps:
- Uninstalled MS4, but not the hub
- Reinstalled MS4, at which point hub did not seem to recognize the sounds were already installed
- Clicked install on a random muse sounds pack, which insta-installed it (probably figured out it was already there)
- Restarted MS4 and was able to activate muse sounds from the playback settings.

**Comment by vttphm** [comment]
Got it working!

**Comment by Fince10086** [comment]
@Tantacrul it's working! thank you

**Comment by eakwarren** [comment]
@Tantacrul Working now. Thanks! I didn't have a ~/Library/Containers/com.muse.hub folder but followed the other steps.

**Comment by iamtesch** [comment]
Thanks all -- yeah, this was due to an incorrect cached setting state left by a bug in an earlier version of the hub; we've verified this is resolved on the newer builds of the hub, so I'll go ahead and close this for now as it shouldn't affect new users.

Thanks again for verifying the fix!

**Comment by Kqpout** [comment]
Hi,
In never installed the Hub or MS4 previously, I just installed Muse Hub (Win10) from the official website and Muse Sounds and I got this problem, so maybe the bug isn't fully fixed

**Comment by Kqpout** [comment]
> Hi, In never installed the Hub or MS4 previously, I just installed Muse Hub (Win10) from the official website and Muse Sounds and I got this problem, so maybe the bug isn't fully fixed

It works after just restarting the computer, though

**Comment by Batwam** [comment]
In installed MuseScore using the Linux flatpak and MuseSounds via MuseHub (deb file) and experience the same issue. I have deleted the flatpak and reinstalled it and the sounds are still shown as `Inactive`. Nothing happens when I right click on the MuseHub logo in the top left so there is not "Uninstall the helper by right-clicking on the Muse Hub logo (top left) and selecting 'Uninstall helper'" step for me.

Anyone manaegd to fix this? Is there a way to do some troubleshooting and figure out what the Sounds are marked as `inactive`? I'm really keen on trying these cool sounds!

**Comment by Tantacrul** [comment]
@Batwam - this is probably best addressed to the MuseHub team, who have set up this new space:
https://musehub.zendesk.com/hc/en-gb
