### ISSUE TITLE
[MU4 Issue] wrong auto generated part names, if multiple instruments have same "part name" in Staff/Part properties

### ISSUE THREAD

**Issue by sammik** [musescore/MuseScore#14163]
**Describe the bug**
If a score has instruments with the same "part name" in Staff/Part properties, auto generated parts have wrong names.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create score with 3 violins and in Staff/Part properties change "part name" to "violin" to each staff / or import MU3 < 3.5 score with 3 (or 2) violins
2. Click Parts button
3. See Part names: 2 x Violin 1, 1 x Violin

**Expected behaviour**
Violin 1, Violin 2, Violin 3

**Screenshots**

https://user-images.githubusercontent.com/1646034/198831428-9eed400a-f584-46da-88e8-849e54ac3645.mp4

**Platform information**
 - OS: [reported on Linux]

**Additional context**
Regression, in MU3 autogenerated "new all" part names are correct

**Comment by sammik** [comment]
Here is "real life" string quartet 3.2.3 score, which is affected with this bug.
In MU3 there are Husle 1, Husle 2, Viola, Violončelo parts.
[Rodný_môj_kraj_SQ.zip](https://github.com/musescore/MuseScore/files/9932853/Rodny_moj_kraj_SQ.zip)

**Comment by DmitryArefiev** [comment]
Fixed in #14288

**Comment by DmitryArefiev** [comment]
@sammik Can you recheck briefly on master if all issues are fixed on your side as well? Thanks!

**Comment by sammik** [comment]
@DmitryArefiev This one is not completely fixed.

"Part name" field was removed from "Staff/Part properties" dialog, which if fine.

But You can still use "replace instrument" which gives You same name multiple times.

And if You do this before opening Parts dialog, you get wrong part names (but this is quite speculative user case)

https://user-images.githubusercontent.com/1646034/201692175-130e491a-8c2e-4445-bfe9-75753979f51a.mp4

Similar problem is in imported older files, if user rename Long instrument name see #14520
