### ISSUE TITLE
[MU4 Task] Add "saving online..." dialog to save to cloud flow

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#14249]
**Task description**
Following some testing feedback, we'd like to implement the following "saving online..." dialog to the Save to Cloud flow: 

<img width="414" alt="Group 1597" src="https://user-images.githubusercontent.com/86290556/199275811-fa15d5d7-640c-49a7-828f-a0dee9a0dc77.png">
 
<img width="1921" alt="10c" src="https://user-images.githubusercontent.com/86290556/199274116-de908a83-5305-45c9-bc13-4fd167ded46b.png">

This dialog would appear whenever the user saves a **private** score to the cloud. 

Just to clarify the flow:
1. The _first_ time the user saves a file, they see the current "Success" dialogs.
2. On every _subsequent_ save, the user will see the above dialog (and _not_ the "Success" dialog). This new dialog will stay on the screen for as long as it takes to upload the file, preventing the user from interacting with the score or repeating further "save" commands.
3. Once the upload is complete, this dialog will simply disappear and the user can carry on with their work.

If any audio is being generated for upload, this new dialog would appear _after_ the audio file has been generated.

Let me know if there are any questions,
and thanks!

@Tantacrul FYI

**Comment by Eism** [comment]
@bkunda 
It is for you https://github.com/musescore/MuseScore/pull/14441

**Comment by bkunda** [comment]
Thanks @Tantacrul,

FWIW I can also reproduce this crash quite easily, without having to close/reopen the score:

https://user-images.githubusercontent.com/86290556/200853648-97388456-ff63-442f-b71d-c96f14476099.mov

https://user-images.githubusercontent.com/86290556/200853663-e6ea641a-c2b2-4466-9000-3af5d1bb8e35.mov

I've checked the latest nightly and the beta build too and am unable to reproduce this crash in either of these builds. 

I also have one other nit-picky request if it can be accommodated. The dimensions of the new "Saving online..." dialog aren't quite what I put in the design file, and I think it's currently a bit too large for the amount of text it needs to contain. 

_Current size _
<img width="237" alt="Screenshot 2022-11-09 at 3 08 14 pm" src="https://user-images.githubusercontent.com/86290556/200854038-116b6076-ce2e-41e8-88a1-2c8347df9286.png">

_Specified size (roughly 338 x 76 px)_
<img width="414" alt="Group 1597" src="https://user-images.githubusercontent.com/86290556/200854136-56f3fd6f-74c5-4e3b-ad17-f52d9cae1a6b.png">

Obviously the crash (and removing the subsequent "success!" dialog triggers) is the main issue of concern here though :-)

**Comment by Eism** [comment]
@Tantacrul @bkunda 
fixed

**Comment by Tantacrul** [comment]
OK, that's better. I did notice one other thing that can cause big problems if there is a small delay, which prompts the user to press **command+s** again, or even multiple times.


https://user-images.githubusercontent.com/21022311/201186663-1eae719e-a35d-4de5-8df0-0ceef478e4ac.mov

**Comment by Eism** [comment]
@Tantacrul 
No, there is no delay. In fact, after closing the 'save online...' dialog, the audio is also uploaded.

Steps:
Export audio (progress dialog) -> upload score (progress dialog) -> show success dialog -> upload audio (without progress dialog)

At the last step, you tried to re-save. 

Now the success dialog is shown after the audio is uploaded. Since these changes are serious, they need to be carefully tested. @bkunda FYI

> Also: if possible it would be useful if the animation was a simple fade-in animation, rather than a scaling animation.
> If that's not a trivial change, then ignore me.

I will ignore you :)

**Comment by Tantacrul** [comment]
@Eism - I think you may have misunderstood.

I have experienced a delay between pressing save and seeing the 'Saving' dialog. For this reason, I pressed 'Save' again, which meant that it saved twice and I saw the 'Saving' dialog twice.

So, my overall point is:

1. When a user triggers save - all other save commands should be ignored until the 'Saving' dialog is closed
2. If we don't do this, then users with massive scores (and possibly uploaded audio too) could end up accidentally having to save and upload audio multiple times.

**Comment by bkunda** [comment]
I've just tested the latest commit from about an hour ago:
I tried hitting ‘Save‘ multiple times on a large score before and while the "Saving online..." dialog was present.
No additional "saves" were triggered (even with audio generation). 
@Tantacrul it's worth you double checking this too to make sure I haven't overlooked anything here.

**Comment by Tantacrul** [comment]
That's odd. I'm still having the exact same problem.

**Comment by bkunda** [comment]
Actually @Eism I too have just been able to reproduce the repeat-saving issue (the audio generation also repeats several times).

**Comment by Eism** [comment]
@Tantacrul @bkunda 
Fixed. Please recheck

**Comment by Tantacrul** [comment]
Still having the same issue:
https://user-images.githubusercontent.com/21022311/201398977-6eda04c7-8fd2-4443-a6ea-ef80d85c00cd.mov

**Comment by Eism** [comment]
@Tantacrul 
Are you sure you are running the correct build? Should be 4.0.0.223151524 (see About MuseScore dialog)
I can't reproduce

**Comment by Tantacrul** [comment]
Also tried resetting factory settings, for what that's worth.

**Comment by Tantacrul** [comment]
@Eism - I don't think the PR updated properly. When you asked me to retest, I did so 20 minutes after your request.

I can now see that the MacOS check occurred 3 hours ago:
<img width="829" alt="image" src="https://user-images.githubusercontent.com/21022311/201402974-4873c60a-12d4-4930-96fc-5629ea93a680.png">

**Comment by shoogle** [comment]
@Tantacrul, the last 4 digits of [your build number](https://github.com/musescore/MuseScore/issues/14249#issuecomment-1312012539) are different to @Eism's [build number](https://github.com/musescore/MuseScore/issues/14249#issuecomment-1312009968).

FWIW, the last 4 digits of the build number show the time at which the build took place (12:40 vs 15:24). The previous digits show the year ('22) and day of year (315 out of 365).

**Comment by Tantacrul** [comment]
Look again @shoogle 

I think @Eism missed the last digit

**Comment by Eism** [comment]
No :)

4.0.0.22315  **1240**         your build (last four digits mean that the build started at 12:40)
4.0.0.22315  **1524**         my build (last four digits mean that the build started at 15:24)

**Comment by shoogle** [comment]
Yes, I thought they were the same at first with just the zero missing off the end, but both numbers have 9 digits. It's just the repeated 15 and 24 that makes them look the same.

**Comment by Tantacrul** [comment]
<img width="465" alt="image" src="https://user-images.githubusercontent.com/21022311/201408073-c880ea5d-5bbd-4502-aa00-8e725b8d8169.png">

OK, my bad. I've tested it now and - yes - the Command+S problem is no longer happening. Thanks!

**Comment by Eism** [comment]
@bkunda 
I've made some changes that might break the score upload. Could you retest?
