### ISSUE TITLE
[MU4 Issue] Preferences > Shortcuts: cannot input a shortcut of the form `Shift` + special key

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#14697]
**To Reproduce**
1. Go to Preferences > Shortcuts
2. Choose an action to define a shortcut for
3. In the popup, try to enter a shortcut of the form <kbd>Shift</kbd> + a special key, for example:
    - Space bar
    - Backspace / delete
    - the <kbd>F1</kbd>...<kbd>F12</kbd> keys
    - Arrow keys

    -> Result: the <kbd>Shift</kbd> key is ignored.

**Expected behavior**
The Shift key should not be ignored.

**Platform information**
 - OS: at least macOS, but probably all of them

**Additional context**
In `src/framework/shortcuts/shortcutstypes.h`, the method `correctKeyInput` actively drops the Shift modifier. I think this is a left-over from MS3's shortcuts system, which worked fundamentally different. The fix is probably as simple as removing this code.

**Comment by cbjeukendrup** [comment]
It might be good to explain the relation between this issue and #14539:
- This issue is about not being able to _enter_ custom shortcuts of a certain form in the "Define shortcut" dialog
- [#14539](https://github.com/musescore/MuseScore/issues/14539) is about custom shortcuts of a slightly different form that _can_ be entered but cannot be _used_.

**Comment by ecstrema** [comment]
> Platform information
> OS: at least macOS, but probably all of them

Indeed, windows is affected too. See #10745

**Comment by xlf1024** [comment]
This also applies to combining Shift with German Umlaut keys Ä Ö Ü or Scandinavian Æ Ø Å. Interestingly, the dialog always shows the uppercase variant; but only the lowercase variant triggers the specified action; Shift+[key] does nothing.

**Comment by avvvvve** [comment]
This also applies to Shift + Arrow keys. Updated the description accordingly.

**Comment by cbjeukendrup** [comment]
Seems fixed in 4.5

**Comment by FrancRos31** [comment]
> Seems fixed in 4.5

Still occurring with Backspace

https://github.com/user-attachments/assets/1da791f5-e558-48b1-860d-223124092d04

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.5.0-250721848, revision: github-musescore-musescore-7c55023
