### ISSUE TITLE
[Muse Hub Issue] Muse Hub macOS: while installing updates, the UI feels unstable

### ISSUE THREAD

**Issue by cbjeukendrup** [musescore/MuseScore#14906]
**Describe the bug**
When Muse Hub on macOS is installing updates, the UI feels a bit unstable. Strange things happen around "Get" buttons and progress indicators. It is difficult to describe more specifically, but here are some screenshots: 

This progress indicator got overlayed with a "GET" button:
<img width="477" alt="Scherm­afbeelding 2022-12-03 om 00 24 58" src="https://user-images.githubusercontent.com/48658420/205405818-8b05499c-bdc4-4ee9-9dc6-1ff1243a0480.png">

Progress button not spinning smoothly, but in wrong tempo and with jumps:

https://user-images.githubusercontent.com/48658420/205406000-78e8ba70-544d-473e-aaec-f467330fb3a6.mov

Progress bar at the bottom often says nothing more than "unknown, Zero KB/sec":
<img width="494" alt="Scherm­afbeelding 2022-12-03 om 00 27 27" src="https://user-images.githubusercontent.com/48658420/205406533-e54fef14-d1fe-4747-8bc2-f562bcdf31e3.png">

Or leaping forth and back strangely: 

https://user-images.githubusercontent.com/48658420/205407047-f73e5ac7-ce57-477a-b2b0-6e13e613a5bc.mov

In Settings > Updates, some strange things are happening too:

https://user-images.githubusercontent.com/48658420/205407266-f9ef9721-b66f-47b5-aab5-623cba77afc8.mov

(especially after clicking the refresh button)

**Comment by iamtesch** [comment]
We just pushed a new update to the hub; can you make sure the hub has updated and test again?  (The update should happen automatically after restarting or manually clicking "check for updates", and the new version should be 0.9.10).

Alternatively, you can uninstall and then reinstall by downloading from musehub.com

**Comment by cbjeukendrup** [comment]
I tried to install the update; when I restarted MuseHub, it did ask me for a password to install the helper, but the version number of the Hub itself is still 0.9.9. Re-checking for updates didn't give anything.

I then downloaded the latest version from musehub.com and installed it; now it does say 0.9.10. I'll wait for the next Muse Sounds updates and re-test.

**Comment by cbjeukendrup** [comment]
I just re-checked in version 0.9.11, but it looks like it hasn't changed very much... still seeing behaviour like this:

https://user-images.githubusercontent.com/48658420/206216818-3c5b04e5-5719-4c5e-9750-1c9add0e3ba3.mov

This was after clicking the "check for updates" button in the Settings tab.

Also, directly after clicking that button, strange things happen there too:

https://user-images.githubusercontent.com/48658420/206217244-4fe91e81-7611-459b-a7df-79c705546a9f.mov

(I just click the button once and do nothing after that)

**Comment by cbjeukendrup** [comment]
It seems better now indeed, let's close this
