### ISSUE TITLE
[MU4 Issue] Issues using shortcut **Shift** + **right arrow** to extend slurs and system text lines

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#14952]
**Describe the bug**
Two parts to this bug, both of which concern the use of the shortcut **Shift** + **&rarr;**:
1. (This now moved to #14992): Slurs can no longer be extended between systems (**regression**: this was apparently fixed by [#10515](https://github.com/musescore/MuseScore/pull/10515))
2. System text lines cannot be extended past the bar in which they are inserted

**To Reproduce**
See demo video:

https://user-images.githubusercontent.com/86290556/205672644-9953a997-788d-41e7-8ddf-a276a7ba1353.mp4

**Expected behavior**
The shortcut **Shift** + **&rarr;** should allow both slurs and system text lines to be extended between systems. The behaviour should basically be the same as for staff text lines and hairpins (which currently work as expected). 

**Platform information**
 - macOS 12.6 (M1)
 - RC

**Additional context**
@Tantacrul Even though the slurs issue is technically a regression, I'm wondering whether it's benign enough to leave it in post-release.

**Comment by Tantacrul** [comment]
If it's a regression on a previously fixed issue, we should fix it here. Also, it's a really bad bug anyway.

**Comment by mike-spa** [comment]
👀

**Comment by DmitryArefiev** [comment]
**Issue №1**. Slurs can no longer be extended between systems (**if attached to the last note in system**) - is not a regression. As I see now, it also happens in MS3 and was not fixed in #10515

But **Issue №2** System text lines cannot be extended past the bar in which they are inserted - is really **regression**. Should be fixed in 4.0

**Comment by mike-spa** [comment]
Issue n.2 started with #14397, which fixed other serious issues. I'm looking into it now

**Comment by Tantacrul** [comment]
Perfect. Thanks both!

**Comment by DmitryArefiev** [comment]
Fixed in #14982

**Comment by DmitryArefiev** [comment]
Issue 2 is fixed. For Issue 1 it's better to create a separate bug.

**Comment by bkunda** [comment]
> Issue 2 is fixed. For Issue 1 it's better to create a separate bug.

@DmitryArefiev done: https://github.com/musescore/MuseScore/issues/14992
