### ISSUE TITLE
Wayland: Context menus and menu bar drop-down menus open in the center of the screen

### ISSUE THREAD

**Issue by vmsh0** [musescore/MuseScore#15285]
**Describe the bug**
When opening a menu from the top menu-bar, the menu appears in the center of the screen.

**To Reproduce**
1. Click on e.g. 'File'

**Expected behavior**
The menu should open just below the corresponding menu-bar item, i.e. the File menu should open right at the top-left of the screen, the Edit menu just slightly right of that, etc.

**Screenshots**
![image](https://user-images.githubusercontent.com/1955497/208253637-1340b8b9-ede0-4290-8baa-f357bfb2d839.png)
![image](https://user-images.githubusercontent.com/1955497/208253646-a4d3a81a-ca42-4f3c-8042-0ef571d5dd1a.png)

**Platform information**

- Arch Linux
- `Linux enhorning 6.0.11-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 02 Dec 2022 17:25:31 +0000 x86_64 GNU/Linux`
- Sway (sway 1:1.7-10)

**Additional context**
This is probably because I'm using a tiling window manager, which spawns floating windows in the center of the screen.

When I open a menu item, I see the following message in the log:

```
18:18:28.220 | WARN  | main_thread | Qt         | QQmlComponent: Created graphical object was not placed in the graphics scene.
```

which seems to boil down to [here](https://github.com/qt/qtdeclarative/blob/5.15/src/qml/qml/qqmlcomponent.cpp#L1309).

I spent a couple hours hacking with your QML scripts, but due to my complete ignorance about Qt I haven't concluded that much. Interestingly, by means of printf-debugging, I have traced the aforementioned warning message from Qt to [this QML function](https://github.com/musescore/MuseScore/blob/cf7e523f726d580ba6c381936c023babd996406d/src/framework/uicomponents/qml/MuseScore/UiComponents/StyledMenuLoader.qml#L43) in your framework. That is, instrumenting that function to:

```
        function loadMenu() {
	    console.error("xxx 1")
            loader.active = true
	    console.error("xxx 2")
        }
```

produced the following console output:

```
18:18:28.212 | ERROR | main_thread | Qt         | loadMenu: xxx 1
18:18:28.220 | WARN  | main_thread | Qt         | QQmlComponent: Created graphical object was not placed in the graphics scene.
18:18:28.221 | ERROR | main_thread | Qt         | loadMenu: xxx 2
```

I pretty much stopped my investigation here as I don't get how the `loader.active = true` line can have the side effect of printing that other message in the same thread (again, I'm basically completely ignorant about Qt).

**Comment by rzvncj** [comment]
FWIW it's not an Arch Linux thing. I'm using MuseScore on Arch Linux as we speak and all menus are where they are supposed to be. _But_, I'm using it with Gnome.

**Comment by Horus645** [comment]
I am currently having the same problem. Also on Arch, but I am using river as a window manager, which is also tiling.

**Comment by vmsh0** [comment]
> I am currently having the same problem. Also on Arch, but I am using river as a window manager, which is also tiling.

Ooops. Looks like you opened the bug while I was investigating the issue, and I didn't bother re-checking for duplicated before posting. Interesting race condition :P

**Comment by vmsh0** [comment]
Some additional information: Sway has an IPC socket that can be accessed e.g. through the `swaymsg` command. This is the output of `swaymsg -t subscribe -m '["window"]'` after clicking on a menu-bar item (e.g. File"): https://paste.sr.ht/~vmsh0/91599474a7cf3f4b6e8c869629013da42ab7e43c

What I see there: the window for the menu is created, and then it is rendered floating.

So my guess is that MuseScore sets the window of the window during creation, or anyway _before_ turning it to floating.

The issue with that logic is that application-provided position information has no meaning for a non-floating window in a tiling window manager, so the window manager probably either just discards it altogether, or at least it ignores it during the non-floating -> floating transformation (instead just putting the window at the center of the screen).

My guess is that the solution would be one of:
- creating the window as a floating window directly
- setting the position _after_ making the window floating

**Comment by Horus645** [comment]
No, I believe the problem is that the *way* the window is being created is "wrong". I *think* what's happening is that `musescore` is asking for a whole new OSwindow, instead of manually making a pop-up window. This is because stuff like browsers and musescore3 all work correctly despite me being in a tiling WM.

**Comment by ntninja** [comment]
I’m curious what the rationale was to actually implement your own menu bar using QML ListView instead of the QML [MenuBar](https://doc.qt.io/qt-5.15/qml-qtquick-controls2-menubar.html)? After a quick review, all I could find was [this commit](https://github.com/musescore/MuseScore/commit/8d6608e1e5903caa7ef450b4c8b29df25743f37e) where this new behaviour was introduced for no apparent reason. Because, to be honest, this issue looks the exact kind of thing one would mess up due to unnecessarily reimplementing things instead of using what’s already there, but hopefully I’m just missing something important here.

A annoying side-effect of this decision is that MuseScore does not integrate with the global menu on KDE – an issue macOS received [a painful-looking workaround](https://github.com/musescore/MuseScore/blob/cf7e523f726d580ba6c381936c023babd996406d/src/appshell/qml/platform/mac/Main.qml) for so it wouldn’t suffer the same fate, and this makes make all the more curious why *that* was seen as preferable by Musescore’s developers over just using QML [MenuBar](https://doc.qt.io/qt-5.15/qml-qtquick-controls2-menubar.html). (And it couldn’t have been a version incompatibility since the entirety of Musescore 4.0’s development targeted Qt 5.15 only and the QML MenuBar was introduced back in Qt 5.10.)

**Comment by cbjeukendrup** [comment]
QML menus and popups can only live inside the main window; they can't exceed its borders. This is because they are no real menus in a real popup window, but they are not more than graphical drawings inside the main window. But for us, it is crucial that popups are not bounded to the main window, in many cases. Therefore we were forced to build a custom solution. 

QML MenuBar (from QtQuick.Controls) is also just a graphical drawing inside a window, so it wouldn't fix any integration with the system's native menubar. What _might_ work is the MenuBar from Qt.labs (https://doc.qt.io/qt-6/qml-qt-labs-platform-menubar.html). But most probably that will only work on _some_ Linux distros with _some_ window managers, if any at all, so we can't fully switch to it on Linux.

The creation of the popup/menu window is still managed via Qt, so we don't have much control about how the native window is created exactly. There is a chance that you can fix this by playing with the so-called window flags of the QWindow.

**Comment by vmsh0** [comment]
> The creation of the popup/menu window is still managed via Qt, so we don't have much control about how the native window is created exactly. There is a chance that you can fix this by playing with the so-called window flags of the QWindow.

Yeah, this is what I suspected after my investigation, and that's why I thought it might have been a Qt bug. Or anyway, something controlled by Qt, which needs to be massaged with the correct flags.

I'll see if I can find the time to play with it a bit more during Christmas break.

**Comment by Ocawesome101** [comment]
For what it's worth, I'm also seeing this issue consistently on Plasma Wayland (KWin, non-tiling).  Just another data point.

**Comment by Eism** [comment]
Also might be related to #11244

**Comment by eshom** [comment]
Can confirm this issue on openSUSE tumbleed (snapshot 20221220) using KDE Plasma wayland.

**Comment by Horus645** [comment]
> But for us, it is crucial that popups are not bounded to the main window, in many cases. Therefore we were forced to build a custom solution.

Do those include these kind of dropdown windows? I can understand it being necessary in many of the other windows musescore creates, but for this particular case, I just can't picture any scenario where it would be necessary for the dropdown window to exceed the main window's borders.

**Comment by shimpe** [comment]
Same problem on endeavourOs with kde + wayland. It makes musescore very hard to use (e.g. changing instruments in the mixer is only possible using keyboard navigation). I think I read somewhere that wayland does not allow specifying explicit window positions for toplevel windows - could be related to this issue? Are menus toplevel windows?

see https://github.com/gotk3/gotk3/issues/397#issuecomment-522357409

**Comment by Gobbel2000** [comment]
I'm seeing the same issue with Arch Linux when running on Wayland (tested sway and Plasma on wayland), but Xorg works fine. 

One interesting observation is that the appimages don't have the same problem. Could different versions of Qt be the cause?

**Comment by ModProg** [comment]
Can confirm, Appimage does work (Arch + Sway (wayland))

**Comment by kanashimia** [comment]
> One interesting observation is that the appimages don't have the same problem. Could different versions of Qt be the cause?

Because they don't have wayland support and are run through Xwayland.
For your custom builds you can set environment variable to achieve same behaviour
`QT_QPA_PLATFORM=xcb mscore`

@rzvncj i'm sure it is the same on gnome, tested it on mutter and same issue occurs, verify that your musescore actually uses wayland.

---

It is obvious that the issue always occurs when using wayland qt platform, please stop repeating the same thing.

**Comment by rzvncj** [comment]
> @rzvncj i'm sure it is the same on gnome, tested it on mutter and same issue occurs, verify that your musescore actually uses wayland.

I'm not using Wayland. I'm on X11.

**Comment by kanashimia** [comment]
Useful resources about qt wayland porting:
1. https://community.kde.org/Guidelines_and_HOWTOs/Wayland_Porting_Notes
2. https://blog.martin-graesslin.com/blog/2015/07/porting-qt-applications-to-wayland

**Comment by shimpe** [comment]
> Because they don't have wayland support and are run through Xwayland. For your custom builds you can set environment variable to achieve same behaviour `QT_QPA_PLATFORM=xcb mscore`

Yes, this works around the issue.

**Comment by ntninja** [comment]
> QML menus and popups can only live inside the main window; they can't exceed its borders. This is because they are no real menus in a real popup window, but they are not more than graphical drawings inside the main window. But for us, it is crucial that popups are not bounded to the main window, in many cases. Therefore we were forced to build a custom solution.

That is very unfortunate. I can totally understand why this NIH approach was taken by MuseScore developers then. Hope I didn’t sound offensive in any way with my previous “this wasn’t a good idea” comment!

> QML MenuBar (from QtQuick.Controls) is also just a graphical drawing inside a window, so it wouldn't fix any integration with the system's native menubar. What _might_ work is the MenuBar from Qt.labs (https://doc.qt.io/qt-6/qml-qt-labs-platform-menubar.html). But most probably that will only work on _some_ Linux distros with _some_ window managers, if any at all, so we can't fully switch to it on Linux.

Yes, it will only work on Linux desktops with global menu integration. It would make sense implement it in addition to the look-alike menubar that you are currently rendering, since using it doesn’t break anything if that desktop feature isn’t available, then provide a keyboard shortcut (Ctrl+M, like KDE apps) to hide the look-alike menubar on-demand. From the API docs I’ve read it does not appear as if it provides any native way to check if the global menu is currently being displayed, although the underlying APIs do provide that capability.

> The creation of the popup/menu window is still managed via Qt, so we don't have much control about how the native window is created exactly. There is a chance that you can fix this by playing with the so-called window flags of the QWindow.

I might do that, along with exposing the global menu through the Qt.labs API. No promises though.

**Comment by plastmassor33** [comment]
Here's the specifically global menu related issue:
https://github.com/musescore/MuseScore/issues/15473

**Comment by mathialo** [comment]
> For what it's worth, I'm also seeing this issue consistently on Plasma Wayland (KWin, non-tiling). Just another data point.

Thought I'd chime in with a similar remark. Also hitting this same issue on Arch running KDE and Wayland (so kwin as the window manager).

**Comment by mxj4** [comment]
IIRC it's a qt wayland bug (sorry can't find the link to that one) in Qt5 and it's fixed in Qt6. No fix for Qt5 since the product is EOL.

**Comment by danielzgtg** [comment]
> No fix for Qt5

KDE fixed it in their apps for Qt5. We can fix it the same way they did.

> Qt6
> Qt5 since the product is EOL.

I'm not installing Qt6 as long as I'm stuck on Plasma 5. I don't want to risk Qt5 breaking KDE and other desktop integrations like input methods.

Once Plasma 6 comes out and my other required stuff moves to Qt6, I will stop caring about Qt5.

**Comment by chunga2020** [comment]
Yet another datapoint: It happens in Qtile on Wayland, but not Qtile on Xorg.  Tested on latest nightly AppImage:

`OS: Arch Linux, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231820502, revision: github-musescore-musescore-7185eb8`

**Comment by cbjeukendrup** [comment]
> It might be related to this bug https://bugreports.qt.io/browse/QTBUG-85297 , it's fixed in Qt 6.4+.

It looks like this fix was cherry-picked to the KDE-patched version of Qt 5.15; there is a small chance that we will switch to that at some point.

But I do have some doubts whether it's really related to that Qt bug; in this issue, the problem seems to be that the menu appears really in the center of the screen, rather than in some random location. Not sure if that's just incidental or that that means that it's a different issue.

**Comment by kbloom** [comment]
Well, if this has been patched into Manjaro's Qt 5.15 package, then it's clearly not working with the Musescore package that they distribute. Would you by chance know which KDE commit this is, or whether it's been distributed by Manjaro or Arch yet?

**Comment by bfields** [comment]
For what it's worth, I can also reproduce on Fedora 39 (with Gnome and Wayland). https://bugzilla.redhat.com/show_bug.cgi?id=2250564

**Comment by rriemann** [comment]
I can reproduce the bug with:

> OS: openSUSE Tumbleweed 20231108, Arch.: x86_64, MuseScore version (64-bit): 4.1.1

The proposal `QT_QPA_PLATFORM=xcb mscore` fixes the problem, but now everything is very small.

**Comment by KorigamiK** [comment]
I can also mention this bug happening on hyprland (wayland) where the drop down menus open as separate windows at the center of the screen.

**Comment by napaalm** [comment]
@cbjeukendrup is there any update?

**Comment by cbjeukendrup** [comment]
Not really unfortunately. You could try if the `master` nightly builds change anything about this, because those use Qt 6.2.4 instead of 5.15. https://musescore.org/en/nightly-builds

**Comment by chunga2020** [comment]
I'm using a MU4.3 prerelease, and things seem okay, if you want to try the nightlies @napaalm .

Version info (Help > About MuseScore Studio): `OS: Arch Linux, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.0-241100504, revision: github-musescore-musescore-89d32c7`

Environment: Sway 1.9 on kernel `6.8.7-arch1-1`

**Comment by cbjeukendrup** [comment]
4.3 is in terms of technologies not very different from 4.2.1 though. The switch to Qt 6 is only part of 4.4 (master).

**Comment by gucio321** [comment]
In on master right now and still have this issue

**Comment by thegreyshadow** [comment]
Confirmed here. I had to force starting the app through XCB in order to get menus resembling something normal. However, I lose the ability to go through menus with the cursor keys. I stil can navigate with the keyboard inside a single menu (e.g., File) but cannot go from one menu to another (e.g., from File to Edit).

Operating System: Slackware 64 current
KDE Plasma Version: 6.0.4
KDE Frameworks Version: 6.2.0
Qt Version: 6.6.3
Kernel Version: 6.9.1 (64-bit)
Graphics Platform: Wayland

**Comment by kamazeuci** [comment]
Confirmed here

Operating System: EndeavourOS 
KDE Plasma Version: 6.0.4
KDE Frameworks Version: 6.2.0
Qt Version: 6.7.0
Kernel Version: 6.6.30-2-lts (64-bit)
Graphics Platform: Wayland

MuseScore version (64-bit): 4.2.1-, revision: github-musescore-musescore- using Qt version 5.15.13.

**Comment by gucio321** [comment]
works for me on 2cb22967dab2843a91bff01e6322432a7997375c

**Comment by cbjeukendrup** [comment]
The `master` branch now uses Qt 6.2.4 instead of 5.15.x, which may have resolved this. Would be great if more people could try, so that we can close this issue.

**Comment by Gobbel2000** [comment]
Unfortunately the problem hasn't changed for me in the latest master with Qt 6.2.4. 

But [this Qt bug](https://bugreports.qt.io/browse/QTBUG-85297), which was linked in this thread earlier is only fixed in Qt 6.4+. I would expect that this is the underlying issue.

**Comment by kanashimia** [comment]
> But [this Qt bug](https://bugreports.qt.io/browse/QTBUG-85297), which was linked in this thread earlier is only fixed in Qt 6.4+. I would expect that this is the underlying issue.

This issue still occurs on MuseScore master and Qt 6.7.1
Had to do some patching to build with new Qt.

<details><summary>Nix code</summary>

```nix
stdenv.mkDerivation (finalAttrs: {
  pname = "musescore";
  version = "4.4.0-unstable";

  src = inputs.musescore;

  cmakeFlags = [
    "-DMUSESCORE_BUILD_MODE=release"
    "-DMUE_BUILD_CRASHPAD_CLIENT=OFF"
    "-DMUE_COMPILE_USE_SYSTEM_FREETYPE=ON"
    "-DMUE_COMPILE_USE_SYSTEM_TINYXML=ON"
    "-DMUE_COMPILE_USE_SYSTEM_OPUSENC=ON"
    "-DMUE_COMPILE_USE_SYSTEM_FLAC=ON"
    "-DMUE_COMPILE_BUILD_MACOS_APPLE_SILICON=ON"
    "-DMUE_COMPILE_INSTALL_QTQML_FILES=OFF"
    "-DMUSE_MODULE_DRAW_USE_QTFONTMETRICS=ON"
  ];

  qtWrapperArgs = [
    "--prefix LD_LIBRARY_PATH : ${lib.makeLibraryPath [ libjack2 ]}"
    "--set ALSA_PLUGIN_DIR ${alsa-plugins}/lib/alsa-lib"
  ];

  nativeBuildInputs = [
    qt6.wrapQtAppsHook
    cmake
    pkg-config
    ninja
  ];

  buildInputs = [
    libjack2
    freetype
    lame
    libogg
    libpulseaudio
    libsndfile
    libvorbis
    portaudio
    portmidi
    flac
    libopusenc
    libopus
    tinyxml-2
    alsa-lib
    qt6.qtbase
    qt6.qtnetworkauth
    qt6.qtdeclarative
    qt6.qtdeclarative
    qt6.qtsvg
    qt6.qttools
    qt6.qt5compat
    qt6.qtscxml
    qt6.qtwayland
  ];

  postPatch = ''
    substituteInPlace src/project/internal/projectactionscontroller.cpp \
      --replace-fail \
        '#include "cloud/clouderrors.h"' \
        '#include "cloud/clouderrors.h"
        #include "cloud/cloudqmltypes.h"'
    substituteInPlace src/appshell/view/navigableappmenumodel.cpp \
      --replace-fail \
        'QList<int> keys = QKeyMapper::possibleKeys(correctedKeyEvent)' \
        'QSet<int> keys; for (auto key: QKeyMapper::possibleKeys(correctedKeyEvent)) keys << key.toCombined();' \
      --replace-fail \
        'QList<int> keys = QKeyMapper::possibleKeys(&fakeKey)' \
        'QSet<int> keys; for (auto key: QKeyMapper::possibleKeys(&fakeKey)) keys << key.toCombined();' \
      --replace-fail \
        'return QSet<int>(keys.cbegin(), keys.cend());' \
        'return keys;'
  '';

  postInstall = ''
    rm -r $out/{include,lib}
  '';

  doCheck = false;
})
```

</details>

**Comment by dgcampbe** [comment]
If it is at all helpful to know, for me the issue doesn't occur normally in the Flatpak version (as it does in my distro's repo version as described above), but I can recreate the issue in the Flatpak version using Flatseal to disable X11 and enabling Wayland.

**Comment by Potajito** [comment]
Same issue on 4.3.2 on arch. Forcing xwayland with QT_QPA_PLATFORM=xcb worksaround that.

KDE Plasma Version: 6.1.2
KDE Frameworks Version: 6.4.0
Qt Version: 6.7.2
Kernel Version: 6.9.9-arch1-1 (64-bit)
Graphics Platform: Wayland
Processors: 12 × AMD Ryzen 5 5600X 6-Core Processor
Memory: 31,3 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3080/PCIe/SSE2
Manufacturer: Gigabyte Technology Co., Ltd.
Product Name: X570 AORUS PRO
System Version: -CF

**Comment by guilletrejo** [comment]
Also happening on 4.3.2 on openSUSE TW:

KDE Plasma Version: 6.1.4
KDE Frameworks Version: 6.5.0
Qt Version: 6.7.2
Kernel Version: 6.10.3-1-default (64-bit)
Graphics Platform: Wayland
Processors: 12 × AMD Ryzen 5 5600 6-Core Processor
Memory: 15.5 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3090/PCIe/SSE2
Product Name: A320M-HDV R4.0

And @Potajito workaround also solved it for me!

> Same issue on 4.3.2 on arch. Forcing xwayland with QT_QPA_PLATFORM=xcb worksaround that.

**Comment by cbjeukendrup** [comment]
Perhaps it's not very productive if we keep growing this thread with "me too" comments, mentioning the same workaround over and over again.
As said, it looks like we cannot do anything about this because we fully rely on Qt for the window creation. Perhaps it can be corrected by setting some window flags or setting the parent of the window or not, but that requires some experimentation so should ideally be done by someone who can reproduce this bug (and apparently, there are plenty of people who can, unfortunately).

**Comment by kbloom** [comment]
I saw a potentially relevant comment about the XDG positioner protocol in a blog post by one of the KDE devs today at https://blog.broulik.de/2024/08/a-fresh-perspective-on-things.

I put a comment asking him whether he knows anything that can help us.

**Comment by kbroulik** [comment]
I’ve had a quick look: your popups aren’t `Qt::Popup` windows [1]. In order for XDG positioner to work, the window needs to be of popup type. You also always need a transient parent for the window (`QWindow::setTransientParent`).

Sadly, I don’t even get a menu bar, it’s just a blank strip at the top when I launch the app, so I cannot investigate what’s up with that. But changing the popups to be of actual popup type at least improves the positioning of some popups (e.g. combobox popups) I got in a way that they’re not placed in the middle of the screen anymore. Then you can investigate fixing the positioning code to not assume absolute coordinate anymore.

[1] https://github.com/musescore/MuseScore/blob/cf7e523f726d580ba6c381936c023babd996406d/src/framework/uicomponents/view/popupwindow/popupwindow_qquickview.cpp#L59

**Comment by Potajito** [comment]
> I’ve had a quick look: your popups aren’t `Qt::Popup` windows [1]. In order for XDG positioner to work, the window needs to be of popup type. You also always need a transient parent for the window (`QWindow::setTransientParent`).
> 
> Sadly, I don’t even get a menu bar, it’s just a blank strip at the top when I launch the app, so I cannot investigate what’s up with that. But changing the popups to be of actual popup type at least improves the positioning of some popups (e.g. combobox popups) I got in a way that they’re not placed in the middle of the screen anymore. Then you can investigate fixing the positioning code to not assume absolute coordinate anymore.
> 
> [1]
> 
> https://github.com/musescore/MuseScore/blob/cf7e523f726d580ba6c381936c023babd996406d/src/framework/uicomponents/view/popupwindow/popupwindow_qquickview.cpp#L59

About the blank strip, I also got that when compiling from git against qt 6.7.2. Maybe something on master is not right, maybe I didn't follow some instructions, but is interesting that we both had the same issue with the blank strip.

**Comment by cbjeukendrup** [comment]
The blank menubar is a Qt 6.5+ issue (see https://github.com/musescore/MuseScore/issues/23980#issuecomment-2282773035 and following comments). That's part of the reason that we're still using 6.2 (the other part of the reason is that we want to support as old macOS versions as possible).

> your popups aren’t Qt::Popup windows

[`Qt::Tool = Qt::Popup | Qt::Dialog`](https://doc.qt.io/qt-6/qt.html#WindowType-enum) though. Do you think we have to drop `Qt::Dialog`, i.e. switch from Qt::Tool to Qt::Popup?

I'll also look into the TransientParent stuff. In `PopupWindow_QQuickView::show`, we do set the transient parent but perhaps that's too late?

**Comment by kbloom** [comment]
So I can't see or test the menubar because I'm building with Qt 6.7.2, but when I changed Qt::Tool to Qt::Popup, it fixed the positioning problem for context menus.

Even though you target Qt 6.2, it would be nice to get the menubar working on the most recent versions of Qt so that Linux distributors who build against the shared system Qt get a working app.

I'm not sure what else I need to test that could be broken by this change.

**Comment by cbjeukendrup** [comment]
The change might break things on other platforms. But if that is the case, for macOS and Windows, that can be easily resolved using `#ifdef`s, and if some Wayland-or-not-Wayland detection turns out to be necessary, I assume that must be possible too.
You're welcome to open a Pull Request for this change; then our testers will check it on all platforms. (I could also open the PR, but you and @kbroulik deserve the credits.)

We're indeed planning to investigate the Qt 6.5+ issues in the not-too-far future, partly because of Linux distributors indeed, and partly because eventually we'll have to upgrade anyway.

**Comment by Eism** [comment]
May be related to https://github.com/musescore/MuseScore/pull/15826. See https://github.com/musescore/MuseScore/pull/24094#issuecomment-2296003377

**Comment by kbloom** [comment]
This bug is probably not caused by the fix to #15826, considering that this
bug is older, and and the fix seems to have nothing to do with how
AppMenuBar is implemented.

Now if you're talking about the missing menu bar in Qt 6.5+, we should file
a separate bug for that, so we don't confused about what we're trying to
solve here.

**Comment by cbjeukendrup** [comment]
By the way, is everyone here _not_ using the "official" AppImage, but distro-provided or self-built versions? Because if I'm not mistaken, the AppImage doesn't ship with Wayland support at all (in MuseScore 4.3 and 4.2 at least) so would always fall back to xcb. Not that it matters anything, but I just want to check my understanding about the Wayland situation.

**Comment by kbloom** [comment]
I prefer to use my distro-provided package, if it works.

**Comment by kanashimia** [comment]
At least on NixOS it is specifically wrapped with QT_QPA_PLATFORM=xcb, judging by the reports here there are quite a lot of packagers who didn't do the same.
You could prefer xcb platform in the application itself, that's how qpwgraph did it for example, there's no need for all of the distributions to add a workaround to fix this.

I personally want Wayland support for the better mixed monitor handling and scaling.

**Comment by cbjeukendrup** [comment]
We're currently considering to make Wayland "opt-in" for 4.4, but _with_ this fix, to take a bit more time to ensure that there are no other blocking issues that nobody discovered yet. Then for 4.5 we hopefully have enough confidence to make it default. On the other hand, I wonder how many people will actually use the opt-in in practice. If only few people do it, we'll probably still not get all bugs found and reported. But maybe it works if we encourage people to try it in the release notes. Any thoughts on this?

**Comment by MarcSabatella** [comment]
> By the way, is everyone here _not_ using the "official" AppImage, but distro-provided or self-built versions? Because if I'm not mistaken, the AppImage doesn't ship with Wayland support at all (in MuseScore 4.3 and 4.2 at least) so would always fall back to xcb.

I’m definitely using the AppImage - bizarre errors from unsupported third party builds are definitely not anything I want to deal with.  And yes, Wayland was disabled at some point (although I remember it worked originally in initial MU4 builds, other than the menu/popup issues).  And that is why I am concerned that it currently is the default - this makes 4.4 worse out of the box than previous MU4 releases, requiring workarounds that were not necessary before.

I’m fine with keeping the *option* of running under Wayland.

**Comment by kanashimia** [comment]
> If only few people do it, we'll probably still not get all bugs found and reported. But maybe it works if we encourage people to try it in the release notes. Any thoughts on this?

It is okay, it will be enough. It needs at least some testing with different Qt versions and compositors before it becomes the default, and when it does then any major issues will already be delt with. Minor issues can be fixed later. And you can revert the default back to X11 in the hotfix if something goes wrong anyways, although it isn't the nicest thing to do.
