### ISSUE TITLE
Bass Clarinet plays wrong note(s) in MS4

### ISSUE THREAD

**Issue by Lumi618** [musescore/MuseScore#16755]
### Issue type

Muse Sounds bug

### Bug description

The "D" note on the bass clarinet plays two notes at once, a half step apart from each other. However, it only does this in one place. I am using the Muse Sounds library.

In the video the first D note is wrong, while the second one plays correctly. 

### Steps to reproduce

Write a D in the treble clef using the bass clarinet sound from Muse Sounds.

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/121732752/224570053-0eb7baf0-464e-4761-84b9-7d809984f36a.mp4

### MuseScore Version

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.0.1-230121751, revision: github-musescore-musescore-9b70a8c

### Regression

I don't know

### Operating system

Windows 11

### Additional context

Before, I was not using the bass clarinet sound for the bass clarinet in my piece, so I am unsure if it was broken the whole time. Using the solo cello from Muse Sounds works just fine, the notes are correct.

**Comment by Lumi618** [comment]
Is this just an issue I'm having? I've since discovered it happens in another place in the same score. Is there a fix for this?

**Comment by MarcSabatella** [comment]
I cannot reproduce this with current MuseScore (4.0.2) and current MuseSounds - be sure to update both.  if you continue to have trouble, please attach the specific score with the problem and describe exactly where this occurs.

**Comment by Lumi618** [comment]
Hello,

I just updated both and am still having the same issue. I tried uploading a musescore file, but it seems I can't do that, so here is a pdf file. The wrong note happens in measure 48 on the "D" note on the bass clarinet. Hopefully this helps. I'll upload anything else you need.

[Lullaby for Trees v19.pdf](https://github.com/musescore/MuseScore/files/11094718/Lullaby.for.Trees.v19.pdf)

**Comment by MarcSabatella** [comment]
Just ZIP the score, or rename it to end in ".zip", and then GitHub will accept it.

**Comment by Lumi618** [comment]
Got it, here it is. 
[Lullaby for Trees v19.zip](https://github.com/musescore/MuseScore/files/11095135/Lullaby.for.Trees.v19.zip)

**Comment by MarcSabatella** [comment]
It plays normally for me.  Are you sure you updated your MuseSounds?  There was an issue fixed in bass clarinet within the past week or so.  Maybe try removing and re-installing the woodwinds.

**Comment by Tantacrul** [comment]
I can reproduce it in 4.1. Just asking the team about it now.

**Comment by Lumi618** [comment]
Ok great! I haven't updated to 4.1 yet, but I can confirm I still have this issue in 4.0.

**Comment by cbjeukendrup** [comment]
Seems fixed by now. If it turns out something similar is still happening, please report it via the Muse Woodwinds page in MuseHub. Thanks!

**Comment by Lumi618** [comment]
Hello! I am still having these issue, I will report via the Muse Woodwinds page soon.
