### ISSUE TITLE
Cannot copy-paste text into save file dialog

### ISSUE THREAD

**Issue by BenWiederhake** [musescore/MuseScore#17133]
### Issue type

UI bug

### Bug description

Copy-pasting text within MuseScore works as expected, but text cannot be copied to the file save dialog. This is especially annoying when I already filled-in the title, and would just like to use *that* as a filename, instead of the default "unknown partiture" filename. Also, I cannot copy-paste text from MuseScore to other applications at all.

(Unrelated: I would even suggest to use the title as default filename, but that's a different story. This issue is about fixing copy-paste behavior.)

### Steps to reproduce

0. Use XOrg, which is the thing through which most Linux systems organize their clipboards. (Note that Wayland should be considered an entirely different thing for this issue.)
1. Open MuseScore, empty partiture
2. Write some fancy title, and copy the text
3. Optional: Paste the text again inside the title field to make extra sure that the text was copied
4. Press Ctrl-S or save through the menu; this should bring up the file save dialog
5. Press Ctrl-V to paste the title as a filename

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/2690845/229838225-64b13f36-c775-4def-8aa4-745233f0838f.mp4

EDIT: Only now I notice that I typo'd the title. Please pretend that I wrote something reasonable like "Long title that I don't want to type *more than* once".

### MuseScore Version

OS: Debian GNU/Linux bookworm/sid, Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230651545, revision: github-musescore-musescore-dbe7c6d

### Regression

I don't know

### Operating system

Debian Bookworm, Xfce 4.18, XOrg

### Additional context

This sounds like some kind of "optimized" interaction between Qt and XOrg. My best guess is that when "copying" the title, nothing is actually copied to the system clipboard, and when "pasting" back into the title field, Qt handles this action completely internally.
This is a good approach for notes and MuseScore-related things, but text *really* should also be exported to the system clipboard.

**Comment by BenWiederhake** [comment]
The behavior improved in MuseScore 4.1.0, but is still buggy (OS: Debian GNU/Linux trixie/sid, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231921359, revision: github-musescore-musescore-2e3a93a)

- Before (4.0.0): No text pasting possible
- Now (4.1.0): Text pasting possible, with unwanted invalid HTML-fragment prepended (see screenshot)
- Desired: Text is pasted unmodified

![Bildschirmfoto_2023-07-16_16-40-55](https://github.com/musescore/MuseScore/assets/2690845/0713614a-0208-4ab9-934f-eeb5782b3d9d)

**Comment by cbjeukendrup** [comment]
I think that that has been fixed by #16242, which will be included in the next update, MuseScore 4.2. Would be great if you could check the latest nightly build! (https://musescore.org/en/nightly-builds)

**Comment by zacjansheski** [comment]
Closing as fixed by https://github.com/musescore/MuseScore/pull/16242

**Comment by scorster** [comment]
Still can't copy Title text in Save As file name in MacOS, MuseScore Studio 4.3.2 

OS: macOS 13.5, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.2-241630832, revision: github-musescore-musescore-22b46f2

As far as I can tell, it's not possible to copy text from any text object and psate it into the MacOS SaveAs file name

**Comment by cbjeukendrup** [comment]
@scorster It would be better to open a new issue for that, because under the hood it's a different problem. 

This issue was about the fact that when copying text from MuseScore, it was not added to the OS clipboard in a way that other apps could understand it. (And the Save dialog is in some sense an "other app", because it is provided by the OS instead of by MuseScore.)

On the other hand, the current problem with the Save dialog is that it does not respond to keyboard shortcuts, so Cmd+C, Cmd+V etc. don't work while the dialog is open. Also, the Copy/Paste/etc items in the "Edit" menu are not hooked up to this dialog but try to send commands to MuseScore's main window. 

As a workaround, I was able to paste the text by right-clicking / ctrl+clicking inside the text field inside the dialog.

Anyway, so it would be great if you could open a new issue for that problem. Thanks in advance!

**Comment by scorster** [comment]
@cbjeukendrup 

sorry, the new form wouldn't enable the Submit button.

Here's the crux of the post I attempted to log. Perhaps you can manage the post.

============

Can't copy Title text and paste into a Save As file name in MacOS 13.5.2, MuseScore Studio 4.3.2. 

As far as I can tell, it's not possible to copy text from any text object and paste it into the MacOS SaveAs file name. **However it is possible to paste Text data outside of MuseScore without including unwanted formatting tags. So based on my very limited testing that part is fixed.**

OS: macOS 13.5, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.2-241630832, revision: github-musescore-musescore-22b46f2

Open a new score
add Title text

Double-click Title text and change it to a new string of chars
Select all
copy Title text

Choose File>SaveAs
Double-click in the dialog's file name field
Paste

**Problem result:** MacOS sounds an alert and no text is pasted.

NOTE: You'll get the same result if you follow the steps above but with a Staff Text object.

**Comment by cbjeukendrup** [comment]
> Sorry, the new beta Issue form wouldn't enable the Submit button.

That probably means that you didn't fill out all the "required" fields. Anyway, no problem, I'm happy to log it myself, and did so here: https://github.com/musescore/MuseScore/issues/23828
