### ISSUE TITLE
Images added to palettes are lost on program restart

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#17456]
### Issue type

UI bug

### Bug description

If you use Ctrl+Shift drag to add an image from your score to a palette, then quit and restart MuseScore, the palette cell is present, but it appears empty, and attempting to add the image to a score produces zero-sized images that may lead to crashes.

### Steps to reproduce

1. copy an image to your clipboard by whatever means is available on your system
2. make sure to have only one instance of MuseScore running
3. select a note or rest in any score
4. press Ctrl+V to add the image
5. Ctrl+Shif+drag the image to a palette of your choice
6. quit MuseScore
7. restart MuseScore
8. open any score
9. open the palette you saved the image to

Result: the palette cell that formerly contained the image remains, but it looks empty.  If you try to add that image to a score, it doesn't appear to work, although depending on whether you click it or use drag & drop, you may end up with a zero-sized image added.

### MuseScore Version

OS: Debian GNU/Linux 11 (bullseye), Arch.: x86_64, MuseScore version (64-bit): 4.0.2-230690504, revision: github-musescore-musescore-dbe7c6d

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Debian 11

### Additional context

If you explicitly save the palette by clicking the "..." and then Save palette, then load the palette into another instance, it works.

**Comment by worldwideweary** [comment]
Hey @MarcSabatella, I just tried this process in the most recent nightly build and I'm not getting the behavior you're describing (although it was happening in an older build). Maybe it got fixed in the meantime? If so maybe it could be marked as fixed...

 Also seems to be some weird discrepancy between debug and release builds  - If in the future you get a build environment as debug compilation, check out this behavior: images don't seem to be showing up in the palettes at all after dragging them into it... and there's an ASSERT that as if forbades it. Kinda makes me wish the travis appimage building system also produced a debug appimage for testing...

**Comment by CynthiaCat** [comment]
I just tried following the steps @MarcSabatella gave above, and I still have the same issue.  I can get the copied image back, but I have to first delete the custom palette it is in and then reload it.

Running Windows 11 Pro, My copy of Musescore tells me I'm running the latest version, but I need help finding out which version that is, precisely. I just checked it on August 25.

**Comment by MarcSabatella** [comment]
To see the version, use Help / About MuseScore.

For me, this is still reproducible with the current version(4.1.1) on Linux.  And it's also still reproducible with the current nightly build, meaning I see no evidence it is fixed yet for an upcoming release either.

**Comment by CynthiaCat** [comment]
Ah, Thank you, Marc. I was looking in the wrong "About" on the Dropdown. To mark the spot, I'm on MuseScore version (64-bit): 4.1.1-232071203, revision: e4d1ddf
@worldwideweary -- You wrote about images not showing up in the palettes after dragging them in. Two points from my experience: To drag an image into a palette, I find that I must first close and then reopen MuseScore and drag the image before doing anything else (other than opening a score, of course.) Second, the image does not show in the palette for me because I run in dark mode. The image is there; it's just also dark, so you can't see it against the dark background. Odd that this only happens with "outside" images. The images from the Master Palette (for example) display white in dark mode.

**Comment by MarcSabatella** [comment]
This is still an issue in 4.4.2, but I have discovered a workaround.  If you paste the image into your score from the clipboard, and then copy to the palette from there, then it is indeed lost from the palette on restart.  *But*, if you instead add the image to a frame via the Add menu, then add to the palette, it works correctly.

I assume the difference is that the pasted-in image has no filename for the palette to reference, but the added-in image does.

**Comment by zk-wgo** [comment]
I have the exact same behaviour as the author described in the initial post. This happens consistently when dragging images to the canvas, then to the palette and then restarting the app. The post above mentions a workaround with a menu command to add images but I cannot find this command in the Add menu. The image is a PNG with transparency.

OS: macOS Sequoia (15.7.3), Arch.: arm64, MuseScore Studio version (64-bit): 4.6.5-253511702, revision: github-musescore-musescore-653f38d

**Comment by MarcSabatella** [comment]
The "Add" menu in question is the context menu (right-click or Ctrl+click) for the frame itself, not the main menu bar.

**Comment by zk-wgo** [comment]
Ok, thank you for clarifying this. I did the whole process then like you described, however for me it still does not work. I added the image to a frame via context menu, then added the image to a palette, then restarted the app and the image was gone, the slot in the palette was still present. 🤷‍♂️ Could it be that your workaround only works on Linux for whatever reason?

**Comment by CynthiaCat** [comment]
I've been having the same issue for over two years now. Unfortunately, I can confirm that Marc's workaround isn't working for me, either. It does behave differently, though. If I drag the image to the palette from a frame, when I restart MuseScore and try to use the image I get two small positioning squares that are parallel and only move on the parallel. If instead I use the same image which I just dragged into the palette (the old way, not the workaround way) I get a box the size of my image with two small positioning squares that move around and size normally, but it's empty. It's like the image has become invisible.

It's very frustrating, but at least there is the workaround of deleting the palette and then using "load palette" to replace it, but you have to do that every time you restart MuseScore if you want it to be available.

I'm running MuseScore version 4.6.5 on a PC running MS Windows 11 pro.

**Comment by Jojo-Schmitz** [comment]
Came up again in https://musescore.org/en/node/389276

**Comment by ridago** [comment]
I tried looking into this today to see if I could figure it out. I've never looked at this code base before, so my understanding may be incorrect, but from what I can tell the issue is that palettes are saved to the workspace, but not the images. Images are only saved to the project file. But palettes are loaded with the workspace, either at startup or when switching workspaces.

This does mean that another workaround is to create a second workspace and swapping to it after loading the score which will then load all the images already in the score.

For an actual fix to the problem I see two possible solutions:

1. Save images with workspaces. Seems like the most sensible fix, but would require adding information to the .mws file. I tested adding pictures to the .mws the same way they are in the project files and they loaded properly, but needs code to recognize the pictures and add them to the store.
2. Reload the workspace after loading the project file. This might be a simpler fix, but would only work for palette images already in the project.

I could potentially look into fixing this, but would like input from someone on the project on what would be an acceptable approach.

**Comment by Jojo-Schmitz** [comment]
Came up again in https://musescore.org/en/node/390550

**Comment by jeetee** [comment]
Option 1 seems the only sensible one IMHO. Palette contents is not linked to a specific score or project and always to the workspace.

Adding elements (be it images or anything else) to a palette has the intention for future reuse, not only within the current score/project.

**Comment by Jojo-Schmitz** [comment]
Came up again in https://musescore.org/en/node/394565

**Comment by mousemom** [comment]
On Mac, I cannot save workspaces. Or rather, I can save them, but they don't appear the next time I launch MuseScore. I even went into Security & Privacy settings and gave MuseScore access to everything. The only workaround I've found is to save the palette. Then upon opening the score, I delete the old custom palette (with missing elements), and reload the custom palette from the saved file.

> For an actual fix to the problem I see two possible solutions:
> 
> 1. Save images with workspaces. Seems like the most sensible fix, but would require adding information to the .mws file. I tested adding pictures to the .mws the same way they are in the project files and they loaded properly, but needs code to recognize the pictures and add them to the store.
> 2. Reload the workspace after loading the project file. This might be a simpler fix, but would only work for palette images already in the project.
> 
> I could potentially look into fixing this, but would like input from someone on the project on what would be an acceptable approach.
