### ISSUE TITLE
No sound with MS Basic when installed in custom path with non-ascii letters (e.g. cyrillic)

### ISSUE THREAD

**Issue by mercuree** [musescore/MuseScore#17518]
### Issue type

General playback bug

### Bug description

First I downloaded nightly build (4.1.0), unpacked it to my download folder (which contains non-ascii letters) and when trying to play some musescore files, there was no sound (MS Basic).
I copied folder to another path with only ascii letters and sound worked fine.
Then I installed official version (4.0.2) and set custom path with non-ascii letters and no sound again.

In logs I see these lines (logs are from nightly, but same thing happens with 4.0.2):
```
2023-05-09T21:44:23.306 | INFO  | main_thread | ActionsDispatcher | dispatch: try call action: file-open
2023-05-09T21:44:24.082 | ERROR | 9808 | <lambda_221c171c8a226b5d13cd98b08dc188db> | operator : Unable to open file 'C:/גרשווין/sound/MS Basic.sf3'
2023-05-09T21:44:24.082 | ERROR | 9808 | <lambda_221c171c8a226b5d13cd98b08dc188db> | operator : fluid_sfloader_load(): Failed to open 'C:/גרשווין/sound/MS Basic.sf3': File does not exists or insufficient permissions to open it.
2023-05-09T21:44:24.082 | ERROR | 9808 | <lambda_221c171c8a226b5d13cd98b08dc188db> | operator : Unable to open file 'C:/גרשווין/sound/MS Basic.sf3'
2023-05-09T21:44:24.082 | ERROR | 9808 | <lambda_221c171c8a226b5d13cd98b08dc188db> | operator : Failed to load SoundFont "C:/גרשווין/sound/MS Basic.sf3"
2023-05-09T21:44:24.082 | ERROR | 9808 | FluidSynth | addSoundFonts: failed load soundfont: C:/גרשווין/sound/MS Basic.sf3
```
I checked those paths and files and they exist.

### Steps to reproduce

1. Install Musescore 4.0.2 to custom folder, which contains non-ascii letters (like cyrillic `абвгд` or hebrew `אבג`)
2. Open musescore file and try to play it

### MuseScore Version

OS: Windows 10 Version 2009, Arch.: x86_64, MuseScore version (64-bit): 4.1.0-231290619, revision: github-musescore-musescore-a5b9dee

### Regression

I don't know

### Operating system

Windows 10 Version 2009

**Comment by mercuree** [comment]
Just in case this information may help:
Since version 2.2.0 FluidSynth supports utf-8 filenames for windows according to this changelog
https://github.com/FluidSynth/fluidsynth/releases/tag/v2.2.0

**Comment by DmitryArefiev** [comment]
The same with release version of MuseScore4

Doesn't occur with **MS3**

**Comment by cbjeukendrup** [comment]
This should be fixed now. Could you please try this in tomorrow's nightly build? https://musescore.org/en/nightly-builds

**Comment by mercuree** [comment]
It works now! Checked on this build https://github.com/musescore/MuseScore/actions/runs/5650512801
However, I still see "Unable to open file "path/to/MS Basic.sf3" in logs. Maybe some fallback loads soundfont after all.
```
2023-07-26T01:02:26.728 | ERROR | 9412 | <lambda_d19bfd5444d2d872e105067d14a389bb> | operator : Unable to open file 'D:/Загрузки/MuseScore-4.2.0.232052238-x86_64/MuseScore-4.2.0.232052238-x86_64_абвгд_еежз/sound/MS Basic.sf3'
2023-07-26T01:02:26.794 | INFO  | 9412 | FluidSynth | addSoundFonts: success load soundfont: D:/Загрузки/MuseScore-4.2.0.232052238-x86_64/MuseScore-4.2.0.232052238-x86_64_абвгд_еежз/sound/MS Basic.sf3
2023-07-26T01:02:26.848 | INFO  | 9412 | FluidSynth | addSoundFonts: success load soundfont: D:/Загрузки/MuseScore-4.2.0.232052238-x86_64/MuseScore-4.2.0.232052238-x86_64_абвгд_еежз/sound/MS Basic.sf3
2023-07-26T01:02:29.860 | INFO  | 9412 | FluidSynth | addSoundFonts: success load soundfont: D:/Загрузки/MuseScore-4.2.0.232052238-x86_64/MuseScore-4.2.0.232052238-x86_64_абвгд_еежз/sound/MS Basic.sf3
2023-07-26T01:02:29.902 | INFO  | 9412 | FluidSynth | addSoundFonts: success load soundfont: D:/Загрузки/MuseScore-4.2.0.232052238-x86_64/MuseScore-4.2.0.232052238-x86_64_абвгд_еежз/sound/MS Basic.sf3
```
