### ISSUE TITLE
ThaLoops VST switching bug/crash

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#18755]
### Issue type

Crash or freeze

### Bug description

When switching between my VSTs by ThaLoops.  One gets stuck on (Pulse). I can get to the other VSTs after switching to a different VST.

However once I return to Pulse I get a crash

### Steps to reproduce

1. Open a score
2. Activate ThaLoops VST "Pulse"
3. Switch to other VSTs such as "Templetone" or "Studio"
4. "Pulse" is stuck on
5. Switch to a different "brand" of VST
6. Now I can open Templetone or Studio
7. At this point, opening Pulse causes a crash

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/69917893/5f9b01bc-5563-4904-ac12-4163870506b9

### MuseScore Version

OS: macOS 11.6, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232021702, revision: github-musescore-musescore-dfdbbec

### Regression

No.

### Operating system

OS: macOS 11.6

### Additional context

Same issues in earlier version of 4.
Crash log attached

[ThatLoopsCrash.zip](https://github.com/musescore/MuseScore/files/12134708/ThatLoopsCrash.zip)

**Comment by CubikingChill** [comment]
@zacjansheski Please have a look at my fix at https://github.com/musescore/MuseScore/issues/16144 . The 3rd commits address cleaning up of VSTs.

**Comment by bkunda** [comment]
We now have a new PR that ports @CubikingChill's fix and adds further fixes. It would be great if this issue could please be retested using this build: https://github.com/musescore/MuseScore/pull/33086

Many thanks!

**Comment by zacjansheski** [comment]
Tested and fixed in https://github.com/musescore/MuseScore/pull/33086

**Comment by CubikingChill** [comment]
> Tested and fixed in https://github.com/musescore/MuseScore/pull/33086

Can you also confirm that the bug is still present in latest nightly?

**Comment by zacjansheski** [comment]
The issue where the vst didn't switch is there, I didn't reproduce the crash.
