### ISSUE TITLE
Slide is not exported to Midi export file (Scorpions - The Sails Of Charon)

### ISSUE THREAD

**Issue by abariska** [musescore/MuseScore#19076]
### Issue type

Other type of issue

### Steps to reproduce

1. Open the gp tab 
[Scorpions - The Sails Of Charon (ver 5 by serojia).gp.zip](https://github.com/musescore/MuseScore/files/12363731/Scorpions.-.The.Sails.Of.Charon.ver.5.by.serojia.gp.zip)
2. Export Lead guitar part to Midi
3. Pay attention to the slide in measure 29

### Screenshots/Screen recordings

![abariska 2023-08-17 at 00 24 12](https://github.com/musescore/MuseScore/assets/101250347/c9ed6dc2-b007-4c90-b23d-9209d003a031)

![abariska 2023-08-17 at 00 26 30](https://github.com/musescore/MuseScore/assets/101250347/21631423-ad1d-4809-b767-0e747ca2f875)

### MuseScore Version

MuseScore 4.1

### Regression

No.

### Operating system

macOS 13

**Comment by alexpavlov96** [comment]
was fixed in https://github.com/musescore/MuseScore/pull/25080/files#r1791748851

**Comment by DmitryArefiev** [comment]
> was fixed in https://github.com/musescore/MuseScore/pull/25080/files#r1791748851

@alexpavlov96 @abariska Checked in **master (4.5)** on Win10. The slide in **measure 29** still doesn't appear in **.mid** file:
![Capture](https://github.com/user-attachments/assets/c6dc1a86-4ded-441a-8544-790d138282c9)
