### ISSUE TITLE
Window Title Bar Does Not Report Aplication Name and Repeats Several Times

### ISSUE THREAD

**Issue by jmwmusic** [musescore/MuseScore#19935]
### Issue type

UI bug

### Bug description

The convention for the main window title bar is to report the application name, as well as any open file.
For example: Untitled - Notepad, or Document1 - Microsoft Word.

MuseScore appears to report only the open score name ... and several times.

This is the text that is shown both in the window title and also the taskbar and Alt+Tab task list windows.

When switching to MuseScore, the title text is often spoken more than once by the screen reader.

### Steps to reproduce

1. Press Windows + D to switch to the Windows desktop.
(In fact, just switch to any other open application with Alt+Tab is also fine)
The focus is now not on the MuseScore application.
2, Press Alt+Tab to switch back to MuseScore.
(Note, there are several other ways to switch tasks and these also yield similar results).
Expected output: Screen reader should read the title and focus of MuseScore, e.g.
Expected behaviour:
Sonata 16 - MuseScore
Actual behaviour:
Sonata 16, Window, Sonata 16, Sonata 16
(or similar with varied amounts of repetition depending on screen reader)

### MuseScore Version

4.1

### Regression

I don't know

### Operating system

Windows 10 with NVDA

**Comment by bkunda** [comment]
@DmitryArefiev FYI

**Comment by DmitryArefiev** [comment]
The second part (Title repeats several times) fixed in #19943 but it's not ready to merge yet (has an issue on Linux)

**Comment by jmwmusic** [comment]
It is nice that this no longer in 4.6 repeats several times, but still does not report the application name, just the file name.  This can be confusing when Alt Tabbing through multiple applications especially if the user has another format file with similar name.
