### ISSUE TITLE
[4.2 Beta] Certain VSTs crashes when replacing

### ISSUE THREAD

**Issue by ShibuyaCyana** [musescore/MuseScore#20341]
### Issue type

Crash or freeze

### Bug description

Just, crashes, recreated by following steps.

### Steps to reproduce

Good news is these two are both free VSTs, and are free to download without registration hassle, and one of them is open source.
So these are the steps:
1. open new score and load any VST;
2. **close its window (important)**;
3. replace it with one of the following will cause a crash:
a. [ChowMatrix](https://github.com/Chowdhury-DSP/ChowMatrix/releases/tag/v1.3.0)
b. [TENSjr](https://klanghelm.com/contents/products/TENSjr)

some observations:
1. simply load these VSTs won't cause a crash, only replacement will
2. it won't crash if step 2 is omitted

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/39703247/9d87cfee-e84f-4fd4-b9e8-1ba1b8389f3d

### MuseScore Version

4.2.0

### Regression

No.

### Operating system

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.0-233260304, revision: github-musescore-musescore-acb1bad

### Additional context

[TENSjr crash.log](https://github.com/musescore/MuseScore/files/13576811/TENSjr.crash.log)
[chowMatrix crash.log](https://github.com/musescore/MuseScore/files/13576813/chowMatrix.crash.log)

**Comment by bkunda** [comment]
@ShibuyaCyana yesterday we merged a fix that _might_ fix this issue, but will need your help to see if it worked. 
Could you please re-test using the latest nightly? Many thanks!

**Comment by ShibuyaCyana** [comment]
No such luck, tested with latest nightly of MuseScore, still crash with the same steps.
MuseScore version info:
OS: Windows 11 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.0-242150305, revision: github-musescore-musescore-6eff80c

**Comment by CubikingChill** [comment]
@ShibuyaCyana Please have a look at my fix at https://github.com/musescore/MuseScore/issues/16144 . The 3rd commits address cleaning up of VSTs.

**Comment by CubikingChill** [comment]
@ShibuyaCyana It seems that my binary fixes this issue.  
https://github.com/CubikingChill/MuseScore/actions/runs/24606167735

**Comment by ShibuyaCyana** [comment]
@CubikingChill Yes, can confirm, no more crashes with the artifact from the link above. Thanks for the fix.

**Comment by bkunda** [comment]
We now have a new PR that ports @CubikingChill's fix and adds further fixes. It would be great if this issue could please be retested using this build: https://github.com/musescore/MuseScore/pull/33086

Many thanks!

**Comment by DmitryArefiev** [comment]
Build from #33086 fixes the crash with **ChowMatrix** and **TENSjr** on my side (Win10), and able to reproduce in 4.7.0-260422045

**Comment by ShibuyaCyana** [comment]
Can confirm - no crash from #33086 artifact.
Sorry, busy days…

**Comment by CubikingChill** [comment]
@ShibuyaCyana No worries. There's just very minor differences from the previous build you tested.
