### ISSUE TITLE
4.2.1 crashes upon loading sounds (Linux, when Opus lib updated to version 1.5)

### ISSUE THREAD

**Issue by dimaugh** [musescore/MuseScore#21838]
### Issue type

Crash or freeze

### Bug description

Musescore crashes upon loading any score. At the terminal, I get:

```
Fatal (internal) error in ../opus-1.5.1/src/opus_decoder.c, line 108: assertion failed: st->stream_channels == 1 || st->stream_channels == 2
Aborted (core dumped)
```

I'm using Arch Linux.

### Steps to reproduce

1. Start Musescore
2. Load any score

### MuseScore Version

4.2.1

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Arch Linux

**Comment by dimaugh** [comment]
I just realized I updated the Opus library yesterday, so it might not be a MS issue after all.

**Comment by DmitryArefiev** [comment]
> I just realized I updated the Opus library yesterday, so it might not be a MS issue after all.

I've checked it on **Ubuntu 22.04.4 LTS** and **MuseScore 4.2.1**. All good on my side

@dimaugh Can you confirm it's on Linux side? Did this happen with the previous versions of MS?

**Comment by dimaugh** [comment]
> @dimaugh Can you confirm it's on Linux side? Did this happen with the previous versions of MS?

I think it has to do with the Opus lib update to version 1.5.1-1, yes. Musescore was installed from the Arch repositories, so it was using the system library. 
I just downloaded the AppImage version and it works fine, I guess it uses an older version of that lib.

**Comment by sealsrock12** [comment]
The same thing happens for me on the Arch package. The AppImage does work fine.

**Comment by pkupper** [comment]
Had the same Problem on Arch. Downgrading the opus package from opus-1.5.1-1 to opus-1.4-1 fixed it.

**Comment by DmitryArefiev** [comment]
@dimaugh So can you confirm the bug not on our side? (to close the issue) 
or we can (should) improve fix on MuseScore side?

**Comment by dimaugh** [comment]
Yes, it has to be an issue with the Opus lib version and not on your side. However, take note to be careful when you decide to upgrade the Opus' version in the AppImage :)

**Comment by Fifis** [comment]
I confirm this issue on the latest Arch with opus 1.5.1 (same error), which is why adding a check / condition for the Opus version could be done temporarily as a temporary bugfix.

**Comment by DmitryArefiev** [comment]
@dimaugh @Fifis Got it. Thanks for info! Closing as 'Not our bug'

**Comment by DmitryArefiev** [comment]
> Yes, it has to be an issue with the Opus lib version and not on your side. However, take note to be careful **when you decide to upgrade to the next Opus version in the AppImage** :)

FYI @igorkorsukov @cbjeukendrup

**Comment by jmvalin** [comment]
If you look at the code that crashed, it's in the validate_opus_decoder() function, which is specifically written to catch a corrupted decoder state. The stream_channels field can never be anything other than 1 or 2, which in all likelihood means that some code in your application had a memory error that caused data to be written over the Opus decoder state. On the next call to Opus, the decoder noticed the inconsistent state and aborted rather than cause more errors. The fact that the problem doesn't happen with 1.4 is likely due to luck about how things get laid out in memory.

Valgrind (and possibly other tools) has a mechanism that allows you to trigger a crash when accessing a certain region of memory. You might be able to use that to figure out what part of the code is trampling on the decoder state.

**Comment by jmvalin** [comment]
Alternatively, you could easily modify libopus to export the validate_opus_decoder() symbol and call that function from your code in a number of places in your code (including before and after calls to Opus).
In all likelihood, you will see that the modification to the state happens outside of Opus.

**Comment by dimaugh** [comment]
@DmitryArefiev , I'm afraid you're gonna have to reopen the issue since it seems to be on your side.

**Comment by cbjeukendrup** [comment]
Let's do so, at least until we reach more confidence about whether or not it's on our side
(Actually, even more likely, it will turn out to be on the Muse _Sounds_ side)

**Comment by andy5995** [comment]
>(Actually, even more likely, it will turn out to be on the Muse _Sounds_ side)

There seems to be some relation.

* OS: Manjaro 23.1.3
* MS: 4.2.1
* opus 1.5.1-1

At MS startup, when I click a score that uses muse-sounds, MS crashes moments later:

>Fatal (internal) error in ../opus-1.5.1/src/opus_decoder.c, line 108: assertion failed: st-stream_channels == 1 || st->stream_channels == 2
Aborted (core dumped)

When I click a score that does not use muse-sounds, it opens normally.

While I have the score open, if I try to open a score that uses muse-sounds, the score opens briefly, then closes, and the original score I opened is still open.

**Comment by Chrisimx** [comment]
Okay, so I debugged MuseScore with GDB to find out what might be the problem. In the application, I opened a score and added a note on a track with a Muse Sound. I had a breakpoint set at the end of the opus_decoder_init function (specifically on the return statement) and at the beginning of the opus_decoder_ctl function, both breakpoints in the MuseScore/thirdparty/opus/src/opus_decoder.c source file. 
I noticed the following things: The memory region where st->stream_channels originally is located actually doesn’t change its contents from the initialization of the OpusDecoder struct in opus_decoder_init (Stacktrace 1) to the failing assert (Stacktrace 2) from what I can tell (meaning its integer value is 2 at both times) But I noticed what might be the cause of the problem: The sampler library code or the system library libopus.so sometimes seems to call into the code linked from MuseScore/thirdparty/opus/src instead of always calling into the one linked from the libopus.so, as the stacktraces show (for example, when creating and initiating the OpusDecoder by running opus_decoder_init (Stacktrace 1)).
When the validate_opus_decoder function is called, in which the failing assert is, it then calls into the code from the system library (libopus.so). Because the version in the "thirdparty" folder is two years old and the system library is a more recent version, there are two differing declarations of the OpusDecoder struct, therefore the memory layout is not the same and there is no binary compatibility. When the validate_opus_decoder function from the system libopus.so accesses st->stream_channels it looks in a vastly different place because it expects another memory layout of the struct than the one the OpusDecoder struct (st) was created with, therefore it fetches the wrong value and the assert fails. So the problem, at least from my view, seems to be that two differing library implementations are linked together in one application. Hope this might help with fixing the bug.

### Attachments

<details><summary>OpusDecoder struct declerations from the current libopus and the one from MuseScore/thirdparty</summary>
<p>

### OpusDecoder struct declaration from MuseScore/thirdparty/opus/src/opus_decoder.c ([Lines on GitHub](https://github.com/musescore/MuseScore/blob/a11f8006d425e30b358bd2fae155d875a5d49a49/thirdparty/opus/src/opus_decoder.c#L55-L79))

```c
struct OpusDecoder {
   int          celt_dec_offset;
   int          silk_dec_offset;
   int          channels;
   opus_int32   Fs;          /** Sampling rate (at the API level) */
   silk_DecControlStruct DecControl;
   int          decode_gain;
   int          arch;

   /* Everything beyond this point gets cleared on a reset */
#define OPUS_DECODER_RESET_START stream_channels
   int          stream_channels;

   int          bandwidth;
   int          mode;
   int          prev_mode;
   int          frame_size;
   int          prev_redundancy;
   int          last_packet_duration;
#ifndef FIXED_POINT
   opus_val16   softclip_mem[2];
#endif

   opus_uint32  rangeFinal;
};
```

### OpusDecoder struct declaration from opus git repo tag v1.5.1 (https://github.com/xiph/opus/blob/ab4e83598e7fc8b2ce82dc633a0fc0c452b629aa/src/opus_decoder.c#L64-L92

```c
struct OpusDecoder {
   int          celt_dec_offset;
   int          silk_dec_offset;
   int          channels;
   opus_int32   Fs;          /** Sampling rate (at the API level) */
   silk_DecControlStruct DecControl;
   int          decode_gain;
   int          complexity;
   int          arch;
#ifdef ENABLE_DEEP_PLC
    LPCNetPLCState lpcnet;
#endif

   /* Everything beyond this point gets cleared on a reset */
#define OPUS_DECODER_RESET_START stream_channels
   int          stream_channels;

   int          bandwidth;
   int          mode;
   int          prev_mode;
   int          frame_size;
   int          prev_redundancy;
   int          last_packet_duration;
#ifndef FIXED_POINT
   opus_val16   softclip_mem[2];
#endif

   opus_uint32  rangeFinal;
};
```

</p>
</details> 

<details><summary>Stacktrace 1 (directly after the note is added, when the OpusDecoder is created)</summary>
<p>

Thread 59 "mscore" hit Breakpoint 19, opus_decoder_init (st=0x7fff6001a730, Fs=48000, channels=2) at /home/chrisimx/CLionProjects/MuseScore/thirdparty/opus/src/opus_decoder.c:156
156	   return OPUS_OK;

```
Backtrace: 
#0  opus_decoder_init (st=0x7fff6001a730, Fs=48000, channels=2) at /home/chrisimx/CLionProjects/MuseScore/thirdparty/opus/src/opus_decoder.c:156
#1  0x00007ffff442099d in opus_multistream_decoder_init (st=st@entry=0x7fff6001a620, Fs=Fs@entry=48000, channels=channels@entry=2, streams=streams@entry=1, coupled_streams=coupled_streams@entry=1, mapping=mapping@entry=0x7fff60001104 "") at ../opus-1.5.1/src/opus_multistream_decoder.c:99
#2  0x00007ffff4420aa1 in opus_multistream_decoder_create (Fs=Fs@entry=48000, channels=channels@entry=2, streams=streams@entry=1, coupled_streams=coupled_streams@entry=1, mapping=mapping@entry=0x7fff60001104 "", error=error@entry=0x7fff75ffe7b4) at ../opus-1.5.1/src/opus_multistream_decoder.c:138
#3  0x00007fffc4806a07 in op_make_decode_ready (_of=_of@entry=0x7fff6000e490) at src/opusfile.c:1369
#4  0x00007fffc48097cf in op_make_decode_ready (_of=0x7fff6000e490) at src/opusfile.c:1353
#5  op_open2 (_of=0x7fff6000e490) at src/opusfile.c:1590
#6  op_open_callbacks (_stream=<optimized out>, _cb=<optimized out>, _initial_data=<optimized out>, _initial_bytes=<optimized out>, _error=0x7fff75ffe844) at src/opusfile.c:1626
#7  0x00007fffc463ea4a in staffpad::files::OggOpusDecoder::OggOpusDecoder(std::shared_ptr<staffpad::files::BinaryInputStream>) () at /usr/lib/libMuseSamplerCoreLib.so
#8  0x00007fffc4679e96 in std::_MakeUniq<staffpad::files::OggOpusDecoder>::__single_object std::make_unique<staffpad::files::OggOpusDecoder, std::shared_ptr<staffpad::files::InputStream>&>(std::shared_ptr<staffpad::files::InputStream>&) () at /usr/lib/libMuseSamplerCoreLib.so
#9  0x00007fffc4679736 in staffpad::vi::SfzRegion::SampleCache::addReference() () at /usr/lib/libMuseSamplerCoreLib.so
#10 0x00007fffc467b422 in staffpad::vi::SfzVoice::SfzVoice(std::shared_ptr<staffpad::vi::SfzRegion>, staffpad::vi::BaseInstrument*, staffpad::vi::VIEvent const&, std::optional<staffpad::vi::VITriggerType>) () at /usr/lib/libMuseSamplerCoreLib.so
#11 0x00007fffc4676ff8 in decltype (::new ((void*)(0)) staffpad::vi::SfzVoice((std::declval<std::shared_ptr<staffpad::vi::SfzRegion>&>)(), (std::declval<staffpad::vi::SfzPlaybackInstrument*>)(), (std::declval<staffpad::vi::VIEvent const&>)())) std::construct_at<staffpad::vi::SfzVoice, std::shared_ptr<staffpad::vi::SfzRegion>&, staffpad::vi::SfzPlaybackInstrument*, staffpad::vi::VIEvent const&>(staffpad::vi::SfzVoice*, std::shared_ptr<staffpad::vi::SfzRegion>&, staffpad::vi::SfzPlaybackInstrument*&&, staffpad::vi::VIEvent const&) () at /usr/lib/libMuseSamplerCoreLib.so
#12 0x00007fffc4671e73 in staffpad::vi::SfzPlaybackInstrument::createVoices[abi:cxx11](staffpad::vi::VIEvent const&, bool, double) () at /usr/lib/libMuseSamplerCoreLib.so
#13 0x00007fffc46513c8 in staffpad::vi::BaseInstrument::processKeyEvents(staffpad::vi::BaseInstrument::KeyData&, staffpad::vi::VIEventList const&, staffpad::audio::Signal32&, bool, double) () at /usr/lib/libMuseSamplerCoreLib.so
#14 0x00007fffc465381a in staffpad::vi::BaseInstrument::process(double, staffpad::vi::VIEventList const&, staffpad::audio::Signal32&) () at /usr/lib/libMuseSamplerCoreLib.so
#15 0x00007fffc46466bb in staffpad::vi::PlaybackEngine::generate(double, staffpad::audio::Signal32&, std::optional<int>, staffpad::vi::PrerenderBuffer const*) () at /usr/lib/libMuseSamplerCoreLib.so
#16 0x00007fffc46d9b3e in staffpad::musesampler::MuseSampler::checkFillBuffer() () at /usr/lib/libMuseSamplerCoreLib.so
#17 0x00007fffc46c95c7 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<staffpad::utils::Timer::Timer(double, std::function<void ()>, bool, std::optional<staffpad::utils::ThreadPriority>)::$_0> > >::_M_run() () at /usr/lib/libMuseSamplerCoreLib.so
#18 0x00007ffff4ce1943 in std::execute_native_thread_routine (__p=0x7fffa8074280) at /usr/src/debug/gcc/gcc/libstdc++-v3/src/c++11/thread.cc:104
#19 0x00007ffff4aa955a in start_thread (arg=<optimized out>) at pthread_create.c:447
#20 0x00007ffff4b26a3c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
```

</p>
</details> 



<details><summary>Stacktrace 2 (in the moment the assert fails):</summary>
<p>

Thread 59 "mscore" received signal SIGABRT, Aborted.
__pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
44	      return INTERNAL_SYSCALL_ERROR_P (ret) ? INTERNAL_SYSCALL_ERRNO (ret) : 0;

```
Backtrace: 
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007ffff4aab393 in __pthread_kill_internal (signo=6, threadid=<optimized out>) at pthread_kill.c:78
#2  0x00007ffff4a5a6c8 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007ffff4a424b8 in __GI_abort () at abort.c:79
#4  0x00007ffff4418467 in celt_fatal (str=<optimized out>, file=<optimized out>, line=<optimized out>) at ../opus-1.5.1/celt/arch.h:79
#5  0x00007ffff4408de2 in validate_opus_decoder (st=0x7fff6001a730) at ../opus-1.5.1/src/opus_decoder.c:108
#6  opus_decode_native (st=0x7fff6001a730, data=<optimized out>, len=<optimized out>, pcm=<optimized out>, frame_size=960, decode_fec=<optimized out>, self_delimited=<optimized out>, packet_offset=0x7fff75ffe6ec, soft_clip=0, dred=0x0, dred_offset=<optimized out>) at ../opus-1.5.1/src/opus_decoder.c:680
#7  0x00007ffff4421438 in opus_multistream_decode_native (st=<optimized out>, data=0x7fff60011bb2 "\374\206\345O\376P\227\244\253?\236{\364?`\227\347\350\372!´\243Y\036\224\227\244+\336\376\332~\276\270\203Y57E\a\323\304\031\004O\352!\242b\377S\375\016\251fO\035\017\321\025\274S\200q\365\364\216\313\353\256\022\346\225B\0058e\275.B\374\216\221\257\362\2466\370\244\277\205\352Ǭsgk[\253mԹ\"\246{W4\203;B\372\265\364@\003\271\351\030\3174E_\026 q\345z\310\322#g+\265\"fȖu\036\356\001\033\231aq;\364_D\251\254ɥ'a\261\n1\rI\356\020\234m\303\304I\241\236\316\v\277\336\357\325Q\370H\035\344\035\032\231\233\365\206\2239\345\360u\226Q!\023τ>\006\346\017\367a8\202", <incomplete sequence \343>, len=275, pcm=pcm@entry=0x7fff601d2ed0, copy_channel_out=copy_channel_out@entry=0x7ffff44174d0 <opus_copy_channel_out_float>, frame_size=frame_size@entry=960, decode_fec=<optimized out>, soft_clip=<optimized out>, user_data=<optimized out>) at ../opus-1.5.1/src/opus_multistream_decoder.c:253
#8  0x00007ffff442190d in opus_multistream_decode_float (st=<optimized out>, data=<optimized out>, len=<optimized out>, pcm=pcm@entry=0x7fff601d2ed0, frame_size=frame_size@entry=960, decode_fec=decode_fec@entry=0) at ../opus-1.5.1/src/opus_multistream_decoder.c:414
#9  0x00007fffc480674f in op_decode (_of=_of@entry=0x7fff6000e490, _pcm=_pcm@entry=0x7fff601d2ed0, _op=_op@entry=0x7fff6000e730, _nsamples=960, _nchannels=_nchannels@entry=2) at src/opusfile.c:2786
#10 0x00007fffc4807d64 in op_read_native (_of=0x7fff6000e490, _pcm=0x7fff601d2ed0, _buf_size=5760, _li=0x0) at src/opusfile.c:2874
#11 0x00007fffc463f3f9 in staffpad::files::OggOpusDecoder::read(staffpad::audio::Signal32&) () at /usr/lib/libMuseSamplerCoreLib.so
#12 0x00007fffc467d38b in staffpad::vi::SfzVoice::cachingRead(int, staffpad::audio::Signal32&) () at /usr/lib/libMuseSamplerCoreLib.so
#13 0x00007fffc467d6a1 in staffpad::vi::SfzVoice::crossfadeRead(int, staffpad::audio::Signal32&) () at /usr/lib/libMuseSamplerCoreLib.so
#14 0x00007fffc467e061 in staffpad::vi::SfzVoice::loopedRead(staffpad::audio::Signal32&) () at /usr/lib/libMuseSamplerCoreLib.so
#15 0x00007fffc4682cd6 in staffpad::vi::SfzVoice::readAndConvertSamples(staffpad::audio::Signal32&) () at /usr/lib/libMuseSamplerCoreLib.so
#16 0x00007fffc467aff2 in staffpad::vi::SfzSampleSource::process(float* const*, int, int) () at /usr/lib/libMuseSamplerCoreLib.so
#17 0x00007fffc4687a60 in staffpad::vi::SfzVoiceProcessorChain::process(staffpad::audio::Signal32&) () at /usr/lib/libMuseSamplerCoreLib.so
#18 0x00007fffc4680c75 in staffpad::vi::SfzVoice::dequeueAudio(int) () at /usr/lib/libMuseSamplerCoreLib.so
#19 0x00007fffc468061e in staffpad::vi::SfzVoice::generate(int) () at /usr/lib/libMuseSamplerCoreLib.so
#20 0x00007fffc4655110 in staffpad::vi::BaseInstrument::KeyData::generate(int, int) () at /usr/lib/libMuseSamplerCoreLib.so
#21 0x00007fffc46523a7 in staffpad::vi::BaseInstrument::processKeyEvents(staffpad::vi::BaseInstrument::KeyData&, staffpad::vi::VIEventList const&, staffpad::audio::Signal32&, bool, double) () at /usr/lib/libMuseSamplerCoreLib.so
#22 0x00007fffc465381a in staffpad::vi::BaseInstrument::process(double, staffpad::vi::VIEventList const&, staffpad::audio::Signal32&) () at /usr/lib/libMuseSamplerCoreLib.so
#23 0x00007fffc46466bb in staffpad::vi::PlaybackEngine::generate(double, staffpad::audio::Signal32&, std::optional<int>, staffpad::vi::PrerenderBuffer const*) () at /usr/lib/libMuseSamplerCoreLib.so
#24 0x00007fffc46d9b3e in staffpad::musesampler::MuseSampler::checkFillBuffer() () at /usr/lib/libMuseSamplerCoreLib.so
#25 0x00007fffc46c95c7 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<staffpad::utils::Timer::Timer(double, std::function<void ()>, bool, std::optional<staffpad::utils::ThreadPriority>)::$_0> > >::_M_run() () at /usr/lib/libMuseSamplerCoreLib.so
#26 0x00007ffff4ce1943 in std::execute_native_thread_routine (__p=0x7fffa8074280) at /usr/src/debug/gcc/gcc/libstdc++-v3/src/c++11/thread.cc:104
#27 0x00007ffff4aa955a in start_thread (arg=<optimized out>) at pthread_create.c:447
#28 0x00007ffff4b26a3c in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
```
</p>
</details>

[full_gdb_console_log.txt](https://github.com/musescore/MuseScore/files/14841188/full_gdb_console_log.txt)

**Comment by jmvalin** [comment]
Yeah, linking to two different version of libopus and (especially) using both on the same object is *definitely* a bad idea. Opus preserves API and ABI compatibility across version, but that does not extend to the memory layout of opaque objects (even compiler flags could break that!).

**Comment by igorkorsukov** [comment]
It turns out that there are no errors in the version of MuseScore that we release, everything works as it should. Error in incorrect assembly.
The problem is an incorrect third-party build for the distribution in question. The one who compiled it, as I understand it, used include files that did not correspond to the new version of the opus.

**Comment by dimaugh** [comment]
Mistery solved. 
Can some Arch user please report it here https://archlinux.org/packages/extra/x86_64/musescore/ ?
I don't have a Gitlab account and new registrations are currently disabled.

**Comment by andy5995** [comment]
I've requested registration.

What changes would you recommend to [this PKGBUILD](https://gitlab.archlinux.org/archlinux/packaging/packages/musescore/-/blob/main/PKGBUILD?ref_type=heads) to correct the problem?

**Comment by Chrisimx** [comment]
I also have an account there and can submit an issue, but honestly I'm a bit critical if this really just a downstream issue. I'm using Arch Linux as well and encountered the same issue with my dev build of musescore. I eventually got it fixed (more about that later). The reason for the problem, at least from what I think, is not just the outdated headers. Actually, it's that
1. the thirdparty/opus directory version doesn't match the system version
2. the compile options don't match
3. that libopus.so is loaded dynamically by libMuseSamplerCore.so and libMuseSamplerCore.so is again loaded dynamically into the mscore object, and at the same time, the mscore object is also statically linked with thirdparty/opus through thirdparty/opusenc
This means there are to different versions of libopus in the same object which, as @jmvalin emphasised, is not good. When other distros update their libopus the same issue will probably happen there as well if the package maintainers aren't very careful.
Really, imho it's not a good/sensible option to both dynamically load a library (which makes it quite possible that it's a different version or, even more likely, at least has different compile flags) and then at the same time statically link to the library built with a possibly different build configuration. Either you link to it statically both times or you link to it dynamically both times, else there will be problems. Since the API and ABI is compatible between different versions of libopus, it might actually be possible to fix the problem quite easily by dynamically linking against libopus both times. But if you want to leave the repo as is, please think about at least leaving a note in the docs so that new devs and packagers know about having to make sure that the version and compile flags of thirdparty/opus match their system lib.

As for the question how the PKGBUILD could be adjusted to work without modifying the MuseScore repo: To fix the issue you first need to delete the thirdparty/opus dir, then download the git repo that matches your system libopus.so into thirdparty/opus (in Arch's case it's tag `v1.5.1`). Then run the `autogen.sh` script in it and finally, configure CMake with the compile options matching libopus.so (in Arch's case at least these `-DOPUS_DRED=ON -DOPUS_DEEP_PLC=ON -DOPUS_OSCE=ON`) and build it. Then it should work and it isn't difficult to update the PKGBUILD to do this (although I still don't think it's the best way to solve it like this)

**Comment by jmvalin** [comment]
Using the wrong version of the headers certainly isn't good practice, but it's also unlikely to lead to particularly bad outcome (especially is the headers are older than the lib). On the other hand, simultaneously linking to two different versions of *any* library is just recipe for disaster. And the actual crash implies that the same object was used with two different versions. There's just no way something like that is going to work -- again with any library.

**Comment by cbjeukendrup** [comment]
Reopening since there isn't really a consensus yet about whether this should be solved in MuseScore itself or not.

**Comment by ShawkMusic** [comment]
This is still happening to me in Musescore 4.3, opus >=1.5

Downgrading to opus 1.4 makes musescore not crash anymore.

**Comment by Chrisimx** [comment]
> This is still happening to me in Musescore 4.3, opus >=1.5 (Arch linux)
> 
> Downgrading to opus 1.4 makes musescore not crash anymore.

@ShawkMusic The reason for this is that the needed build flag is not present in the release v4.3.0 version (f037257). Another build flag (MUE_COMPILE_USE_SYSTEM_OPUSENC) which could be used to fix the crash was backported to the 4.3.0 branch, but the arch package is based on the original release commit and not on that branch. The main problem is that the package maintainer didn't write something yet in the corresponding issue on the Arch gitlab (https://gitlab.archlinux.org/archlinux/packaging/packages/musescore/-/issues/4), so it's a bit unclear how and if they intent to fix it. When 4.3.1 is released there will be at the latest a build flag which could easily fix this issue. I'll probably create a PR on the Arch gitlab then and hopefully they'll accept that. There are however also ways to fix it right now (for example the could be based package on the 4.3.0), but this should be discussed on the Arch gitlab

**Comment by cbjeukendrup** [comment]
FWIW, by now, 4.3.2 is out, which should indeed contain the necessary build flag
