### ISSUE TITLE
MuseScore 4.4 master doesn't see VSTi and VSTe

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#22287]
### Bug description

Recent regression (worked 29.03)

### Steps to reproduce

1. Open Mixer and Sound popup (**FIXED**)

### Screenshots/Screen recordings

![Untitled](https://github.com/musescore/MuseScore/assets/90187801/84b602ba-e8a3-4b9a-8644-45b162965302)

Also, there are another issues:

2. It's scanning VST plugins each time (**FIXED**)

3. VST3 folder is missing in Preferences (**FIXED**)

https://github.com/musescore/MuseScore/assets/90187801/46b6f3e0-5da7-46cd-90e9-07b1a57448e0

### MuseScore Version

4.4.241000304 master

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Win/Mac

**Comment by igorkorsukov** [comment]
fixed

**Comment by DmitryArefiev** [comment]
3. VST3 folder is missing in Preferences. This **still occurs** in master

**Comment by DmitryArefiev** [comment]
> 3. VST3 folder is missing in Preferences

This works fine in latest master build (Win/Mac)

Closing
