### ISSUE TITLE
Pedal sometimes doesn't release on VST instruments

### ISSUE THREAD

**Issue by Riley-Sullivan** [musescore/MuseScore#22910]
### Issue type

VST bug

### Bug description

On the Pianoteq VST (and maybe other VSTs) the pedal sometimes doesn’t release.

### Steps to reproduce

1. Download and install the free demo of Pianoteq 8 from https://www.modartt.com/try
2. Make a new piano score and choose Pianoteq 8 as the instrument.
3. Enter notes across two measures and add a pedal marking to each measure.
4. Change note lengths (or just save, close, and reopen score).
5. Hit play. The pedal doesn’t release between measures one and two.

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/163907533/28063d6c-b70a-4d4e-a0b9-162eb70bb0a4

### MuseScore Version

4.3

### Regression

I don't know

### Operating system

macOS 12.7.2

### Additional context

Note that pedal playback will still be messed up even if you undo.
Only tested on Pianoteq.
Does not affect MS Basic, nor Muse Sounds.

**Comment by Riley-Sullivan** [comment]
What additional info is needed for this issue?

**Comment by oktophonie** [comment]
'needs info' isn't necessarily a label for whoever reports the issue - it's for us internally so we can do our own investigations to work out how to prioritise this and how to approach fixing it.

**Comment by Riley-Sullivan** [comment]
Ah, I see. I wondered if you maybe needed to confirm if this issue affects other VSTs.

**Comment by bkunda** [comment]
@Riley-Sullivan yesterday we merged a fix that _might_ fix this issue, but will need your help to see if it worked. 
Could you please re-test using the latest nightly? Many thanks!

**Comment by Riley-Sullivan** [comment]
Sorry for the late reply Bradley. I can confirm that the issue is NOT resolved as of the August 5 nightly.

**Comment by UlikGames** [comment]
I also have same issue on KV_Element which I use it for Garritan CFX Concert Grand. I also had this issue some Kontakt libraries forex Noire 2 and Galaxy Grand

**Comment by nash-an** [comment]
I am having this same issue still on MuseScore 4.6.4, with Pianoteq 8. I checked the Pianoteq MIDI log, and it seems MuseScore is sending the signals properly. Sustain ends and starts with a 0.001 second delay. This issue does not occur with soundfonts (such as the default Windows one).

<img width="457" height="193" alt="Image" src="https://github.com/user-attachments/assets/b18edc16-f345-4c7e-9f32-e4c42171acfd" />

Is the issue possibly just with the VST not registering that 0.001 second long enough to distinctly trigger both an end and a start to the sustain? Could we maybe add a custom delay in MuseScore? (Moving the end of the sustain does not work as it moves in intervals of 1 note)

**Comment by Riley-Sullivan** [comment]
And also, I can confirm that the issue also affects the newly released Pianoteq 9.
