### ISSUE TITLE
Bass Clarinet (Muse Sounds) Specific Incorrect Playback/Pitch

### ISSUE THREAD

**Issue by JacobPicking** [musescore/MuseScore#23123]
### Issue type

Muse Sounds bug

### Bug description

Bass clarinet playback plays the wrong pitch (half step up) when attempting to play with the following conditions:
1. The note is concert Eb4 (works with any other instrument as long as bass clarinet is the MuseSound used in the mixer)
2. A piano dynamic marking is added
3. The note in question is played either after a rest or is the first note played by the user hitting play.

The playback is normal if other notes precede it, so this issue is only occurring after silences (either rests in the score or because the playback has just been started).

Additionally, if the bugged note is followed by another pitch, the correct pitch is heard briefly before moving to the second note.

I have only found this issue in the bass clarinet. Playback for the same notes is correct for other MuseSounds instruments when changed in the mixer. 

### Steps to reproduce

With the Bass Clarinet Muse-Sound selected in the mixer:
1. Notate a concert Eb4
2. Notate the note with a piano dynamic
3. Have rests precede the note in question, or start the playback directly from this note.
4. Hit Play

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/156558407/b80a7e9a-3496-45ad-b606-2d753c1acd64

### MuseScore Version

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.3.1-241490900, revision: github-musescore-musescore-026c26b

### Regression

I don't know

### Operating system

Windows 11

**Comment by sampleeditor** [comment]
Resolved and released to beta

**Comment by Activebits** [comment]
I'm testing nightly build (OS: Windows 11 Version 24H2 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.6.0-252270411, revision: github-musescore-musescore-15e9633).
**This bug is still here** but more complex than stated above. The combination of MuseSounds Bass Clarinet and the note written Eb 5 in the treble clef (concert pitch) still plays a semitone high if the dynamic marking is ppp, pp, p.
1) It doesn't matter whether there are rests or not before the note.
2) The dynamic doesn't have to be on the note, it can precede it to cause this problem.

<img width="1158" height="184" alt="Image" src="https://github.com/user-attachments/assets/bf4b528f-d038-4ef8-a090-9e54437205e8" />
In the above example, the first two notes (E) sound correctly. When the subsequent Ebs sound, you can hear both E and Eb played together. The Eb tails off and the E persists until that is the only pitch sounding.

The only requirement for this bug to appear is sounding this pitch when a 'p' or quieter dynamic is in effect:

<img width="1201" height="440" alt="Image" src="https://github.com/user-attachments/assets/209bdd20-31a2-4476-9eb3-ba90c4775bde" />

If you change the dynamic in bar 1 from p to mp or louder, the effect goes away.

**Comment by quiviler** [comment]
Came here to see if someone else had this issue. Eb4 at piano dynamic is sounding as E4 instead. Changing the dynamic prevents the issue. Also occurs at pp and ppp dynamics, no other dynamics noted as having this issue.

<img width="771" height="112" alt="Image" src="https://github.com/user-attachments/assets/703d15d6-cd83-4af2-9d41-e014f5283ba0" />

**Comment by sampleeditor** [comment]
Can't reproduce on dev side. 
@quiviler is your example in C or transposing Bb Bass Clarinet? Can you please provide a sample score as transcribing your example results in normal playback??
