### ISSUE TITLE
Trying to move brackets with Shift+Arrows causes a crash

### ISSUE THREAD

**Issue by ykahveci** [musescore/MuseScore#24348]
### Issue type

Crash or freeze

### Description with steps to reproduce

1. Create a score with two linked staves (such as the brace that connects the two staves for a solo piano)
2. Select the bracket / brace
3. Hold shift and press one of the arrow keys (with the intention of spanning the brace across more or less staves)
4. Notice the application crashing

(Crash occurs consistently)

### Supporting files, videos and screenshots

[mscore-diag-info.zip](https://github.com/user-attachments/files/16825762/mscore-diag-info.zip)

<details><summary>Output to stdout</summary>
<pre>

19:28:34.783 | INFO  | main_thread     | GlobalModule::onPreInit | log path: /home/**REDACTED**/.local/share/MuseScore/MuseScore4/logs/MuseScore_240831_192834.log
19:28:34.783 | INFO  | main_thread     | GlobalModule::onPreInit | === Started MuseScore 4.3.2, build number  ===
19:28:34.783 | INFO  | main_thread     | LanguagesService::effectiveLanguageCode | System language code: "en-US" 
19:28:34.784 | INFO  | main_thread     | IpcSocket::connect | success connected to ipc server
19:28:34.869 | WARN  | main_thread     | DiagnosticsModule::onInit | crash handling disabled
19:28:34.965 | DEBUG | main_thread     | LinuxAudioDriver::open | Connected to default
19:28:34.965 | ERROR | main_thread     | MuseSamplerLibHandler::MuseSamplerLibHandler | Unable to open MuseSampler library, path: /home/**REDACTED**/.local/share/MuseSampler/lib/libMuseSamplerCoreLib.so
19:28:34.965 | ERROR | main_thread     | MuseSamplerResolver::doInit | Incompatible MuseSampler library; ignoring
19:28:34.965 | ERROR | main_thread     | MuseSamplerLibHandler::MuseSamplerLibHandler | Unable to open MuseSampler library, path: libMuseSamplerCoreLib.so
19:28:34.965 | ERROR | main_thread     | MuseSamplerResolver::doInit | Incompatible MuseSampler library; ignoring
19:28:34.966 | DEBUG | main_thread     | ShortcutsRegister::expandStandardKeys | removed 5 shortcut, because they are not bound to standard key
19:28:34.966 | DEBUG | main_thread     | ShortcutsRegister::expandStandardKeys | added 3 shortcut, because they are alternative shortcuts for the given standard keys
19:28:34.968 | DEBUG | main_thread     | ShortcutsRegister::expandStandardKeys | removed 219 shortcut, because they are not bound to standard key
19:28:34.973 | WARN  | main_thread     | AbstractCloudService::readTokens | Could not find the tokens file: /home/**REDACTED**/.local/share/MuseScore/MuseScore4/musescorecom_cred.dat
19:28:34.973 | WARN  | main_thread     | AbstractCloudService::readTokens | Could not find the tokens file: /home/**REDACTED**/.local/share/MuseScore/MuseScore4/audiocom_cred.dat
19:28:35.157 | DEBUG | main_thread     | InstrumentTemplate::read | InstrumentTemplate:: init instrument <contrabass> not found
19:28:35.160 | DEBUG | main_thread     | AlsaMidiInPort::connect | Connected to -1
19:28:35.161 | DEBUG | main_thread     | AlsaMidiOutPort::connect | Connected to -1
19:28:35.180 | DEBUG | main_thread     | Score::tick2segment | no measure for tick -1
19:28:35.207 | DEBUG | main_thread     | Score::tick2segment | no measure for tick -1
19:28:35.212 | DEBUG | main_thread     | WorkspacesDataProvider::rawData | get data from default workspace, key: ui_settings
19:28:35.212 | DEBUG | main_thread     | WorkspacesDataProvider::rawData | get data from default workspace, key: ui_states
19:28:35.212 | DEBUG | main_thread     | WorkspacesDataProvider::rawData | get data from default workspace, key: ui_toolconfigs
19:28:35.212 | DEBUG | main_thread     | UiActionsRegister::updateEnabledAll | currentCtx: UiCtxUnknown
19:28:35.216 | DEBUG | main_thread     | Score::tick2segment | no measure for tick -1
19:28:35.224 | DEBUG | main_thread     | Score::tick2segment | no measure for tick -1
19:28:35.226 | DEBUG | main_thread     | WorkspacesDataProvider::rawData | get data from default workspace, key: palettes
19:28:35.226 | DEBUG | main_thread     | PaletteWorkspaceSetup::setup | there is palette data in the workspace, we will use it
19:28:35.228 | DEBUG | main_thread     | TextBase::createBlocks | unknown symbol <noSym>
19:28:35.229 | DEBUG | main_thread     | TextBase::createBlocks | unknown symbol <noSym>
19:28:35.229 | DEBUG | main_thread     | TextBase::createBlocks | unknown symbol <noSym>
19:28:35.230 | DEBUG | main_thread     | TextBase::createBlocks | unknown symbol <noSym>
19:28:35.230 | DEBUG | main_thread     | TextBase::createBlocks | unknown symbol <noSym>
19:28:35.231 | DEBUG | main_thread     | TextBase::createBlocks | unknown symbol <noSym>
19:28:35.624 | DEBUG | main_thread     | UiActionsRegister::updateEnabledAll | currentCtx: UiCtxUnknown
19:28:35.792 | ERROR | main_thread     | App::run        | error: qrc:/qml/MuseScore/UiComponents/FlatButton.qml:179:5: QML Loader: Binding loop detected for property "itemImplicitWidth"

19:28:35.792 | WARN  | main_thread     | Qt              | qrc:/qml/MuseScore/UiComponents/FlatButton.qml:179:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
19:28:35.793 | ERROR | main_thread     | App::run        | error: qrc:/qml/MuseScore/UiComponents/FlatButton.qml:179:5: QML Loader: Binding loop detected for property "itemImplicitWidth"

19:28:35.793 | WARN  | main_thread     | Qt              | qrc:/qml/MuseScore/UiComponents/FlatButton.qml:179:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
19:28:35.794 | ERROR | main_thread     | App::run        | error: qrc:/qml/MuseScore/UiComponents/FlatButton.qml:179:5: QML Loader: Binding loop detected for property "itemImplicitWidth"

19:28:35.794 | WARN  | main_thread     | Qt              | qrc:/qml/MuseScore/UiComponents/FlatButton.qml:179:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
19:28:35.794 | ERROR | main_thread     | App::run        | error: qrc:/qml/MuseScore/UiComponents/FlatButton.qml:179:5: QML Loader: Binding loop detected for property "itemImplicitWidth"

19:28:35.794 | WARN  | main_thread     | Qt              | qrc:/qml/MuseScore/UiComponents/FlatButton.qml:179:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
19:28:35.795 | ERROR | main_thread     | App::run        | error: qrc:/qml/MuseScore/UiComponents/FlatButton.qml:179:5: QML Loader: Binding loop detected for property "itemImplicitWidth"

19:28:35.795 | WARN  | main_thread     | Qt              | qrc:/qml/MuseScore/UiComponents/FlatButton.qml:179:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
19:28:35.796 | ERROR | main_thread     | App::run        | error: qrc:/qml/MuseScore/UiComponents/FlatButton.qml:179:5: QML Loader: Binding loop detected for property "itemImplicitWidth"

19:28:35.796 | WARN  | main_thread     | Qt              | qrc:/qml/MuseScore/UiComponents/FlatButton.qml:179:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
19:28:35.796 | ERROR | main_thread     | App::run        | error: qrc:/qml/MuseScore/UiComponents/FlatButton.qml:179:5: QML Loader: Binding loop detected for property "itemImplicitWidth"

19:28:35.796 | WARN  | main_thread     | Qt              | qrc:/qml/MuseScore/UiComponents/FlatButton.qml:179:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
19:28:35.797 | ERROR | main_thread     | App::run        | error: qrc:/qml/MuseScore/UiComponents/FlatButton.qml:179:5: QML Loader: Binding loop detected for property "itemImplicitWidth"

19:28:35.797 | WARN  | main_thread     | Qt              | qrc:/qml/MuseScore/UiComponents/FlatButton.qml:179:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
19:28:35.797 | ERROR | main_thread     | App::run        | error: qrc:/qml/MuseScore/UiComponents/FlatButton.qml:179:5: QML Loader: Binding loop detected for property "itemImplicitWidth"

19:28:35.797 | WARN  | main_thread     | Qt              | qrc:/qml/MuseScore/UiComponents/FlatButton.qml:179:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
19:28:36.519 | DEBUG | main_thread     | onFireOpen      | try open uri: musescore://home, page: {"modal":"","params":{"sync":true},"path":"","sync":true,"type":1,"uri":"musescore://home"}
19:28:36.604 | ERROR | main_thread     | ScoreThumbnailLoader::loadThumbnail | Could not load thumbnail for "/home/**REDACTED**.mid" : [21] [21] 
19:28:36.605 | DEBUG | main_thread     | UiActionsRegister::updateEnabledAll | currentCtx: UiCtxHomeOpened
19:28:36.797 | ERROR | main_thread     | ScoreThumbnailLoader::loadThumbnail | Could not load thumbnail for "/home/**REDACTED**.mid" : [21] [21] 
19:28:36.798 | ERROR | main_thread     | ScoreThumbnailLoader::loadThumbnail | Could not load thumbnail for "/home/**REDACTED**.mid" : [21] [21] 
19:28:37.356 | INFO  | main_thread     | ActionsDispatcher::dispatch | try call action: file-new
19:28:37.356 | DEBUG | main_thread     | onFireOpen      | try open uri: musescore://project/newscore, page: {"modal":"","params":{"sync":true},"path":"MuseScore/Project/NewScoreDialog.qml","sync":true,"type":2,"uri":"musescore://project/newscore"}
19:28:37.393 | ERROR | main_thread     | App::run        | error: qrc:/qml/MuseScore/Project/internal/NewScore/KeySignatureSettings.qml:118:13: QML KeySignatureListView: Binding loop detected for property "rows"

19:28:37.393 | WARN  | main_thread     | Qt              | qrc:/qml/MuseScore/Project/internal/NewScore/KeySignatureSettings.qml:118:13: QML KeySignatureListView: Binding loop detected for property "rows"
19:28:37.473 | DEBUG | main_thread     | UiActionsRegister::updateEnabledAll | currentCtx: UiCtxHomeOpened
19:28:37.474 | DEBUG | main_thread     | UiActionsRegister::updateEnabledAll | currentCtx: UiCtxHomeOpened
19:28:37.474 | DEBUG | main_thread     | UiActionsRegister::updateEnabledAll | currentCtx: UiCtxUnknown
19:28:39.158 | DEBUG | main_thread     | UiActionsRegister::updateEnabledAll | currentCtx: UiCtxUnknown
19:28:40.075 | DEBUG | main_thread     | UiActionsRegister::updateEnabledAll | currentCtx: UiCtxUnknown
19:28:40.824 | DEBUG | main_thread     | UiActionsRegister::updateEnabledAll | currentCtx: UiCtxUnknown
19:28:40.824 | WARN  | main_thread     | Score::endCmd   | no command active
19:28:40.824 | DEBUG | main_thread     | ScoreLayout::layoutRange | empty score
19:28:40.840 | DEBUG | main_thread     | XmlWriter::tagProperty | property value type mismatch, prop: barLineSpan
19:28:40.844 | INFO  | main_thread     | NotationProject::doSave | success save file: "/home/**REDACTED**/.local/share/MuseScore/MuseScore4/new_project.mscz" 
19:28:40.847 | DEBUG | main_thread     | UiActionsRegister::updateEnabledAll | currentCtx: UiCtxUnknown
19:28:40.859 | DEBUG | main_thread     | UiActionsRegister::updateEnabledAll | currentCtx: UiCtxHomeOpened
19:28:40.865 | DEBUG | main_thread     | onFireOpen      | try open uri: musescore://notation, page: {"modal":"","params":{"sync":true},"path":"","sync":true,"type":1,"uri":"musescore://notation"}
19:28:40.868 | DEBUG | main_thread     | WorkspacesDataProvider::setRawData | set data to default workspace, key: ui_states
19:28:41.038 | DEBUG | main_thread     | UiActionsRegister::updateEnabledAll | currentCtx: UiCtxHomeOpened
19:28:41.042 | DEBUG | main_thread     | UiActionsRegister::updateEnabledAll | currentCtx: UiCtxNotationFocused
19:28:41.054 | ERROR | 126110794778304 | SynthResolver::resolveSynth | invalid audio source params for trackId: 0
19:28:41.060 | DEBUG | 126110794778304 | FluidSynth::init | synth inited

19:28:41.098 | INFO  | 126110794778304 | FluidSynth::addSoundFonts | success load soundfont: /usr/share/mscore-4.3/sound/MS Basic.sf3
19:28:41.100 | INFO  | 126110794778304 | FluidSynth::addSoundFonts | success load soundfont: /usr/share/mscore-4.3/sound/MS Basic.sf3
19:28:41.100 | DEBUG | 126110794778304 | FluidSynth::init | Selected preset 'Grand Piano' on channel 0
19:28:41.445 | DEBUG | 126109802825408 | Score::tick2segment | no measure for tick -1
19:28:42.126 | ERROR | 126110794778304 | SynthResolver::resolveSynth | invalid audio source params for trackId: 1
19:28:42.130 | DEBUG | 126110794778304 | FluidSynth::init | synth inited

19:28:42.131 | INFO  | 126110794778304 | FluidSynth::addSoundFonts | success load soundfont: /usr/share/mscore-4.3/sound/MS Basic.sf3
19:28:42.131 | INFO  | 126110794778304 | FluidSynth::addSoundFonts | success load soundfont: /usr/share/mscore-4.3/sound/MS Basic.sf3
19:28:42.132 | DEBUG | 126110794778304 | FluidSynth::init | Selected preset 'Standard' on channel 0
19:28:43.657 | DEBUG | main_thread     | UiActionsRegister::updateEnabledAll | currentCtx: UiCtxNotationFocused
19:28:43.742 | DEBUG | main_thread     | Score::endCmd   | Undo stack current macro child count: 0
19:28:44.426 | DEBUG | main_thread     | Score::endCmd   | Undo stack current macro child count: 0
19:28:44.704 | DEBUG | main_thread     | Score::startCmd | Score::startCmd(): cmd already active
[1]    1068824 segmentation fault (core dumped)  mscore

</pre>
</details> 

https://github.com/user-attachments/assets/543c8a46-63a9-44dc-b9e4-c7f5bb539f90

### What is the latest version of MuseScore Studio where this issue is present?

4.3.2

### Regression

I was unable to check

### Operating system

Arch Linux

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by zacjansheski** [comment]
Seems to only occur on Linux (I can only reproduce on my Linux device)

Not a regression, I can reproduce in all versions of 4

@cbjeukendrup could you please look at the diagnostic files?

**Comment by cbjeukendrup** [comment]
The diagnostic files don't contain a crash dump unfortunately (I doubt that works on Linux at all). And the log files don't contain any direct hint either.

However this might have been fixed by https://github.com/musescore/MuseScore/pull/24714, which also fixed some not-really-explicable Linux crashes. That PR was included in 4.4.3, so it would be good to check if this still happens in that version.

**Comment by MarcSabatella** [comment]
Shift+Left with a bracket selected still crashes reliably for me on Linux in both 4.4.3 and current master, not that this is a meaningful action to try.  But Shift+Down also crashes, *if* there is another staff below that I could possibly extend the bracket to.  It also will crash less reliably even without a second instrument, often only on the second try.
