### ISSUE TITLE
Various glitches in normal and full screen mode (Windows)

### ISSUE THREAD

**Issue by FrancRos31** [musescore/MuseScore#24586]
### Issue type

UI bug (incorrect info or interface appearance)

### Description with steps to reproduce

1. Open the app
2. press F11 to toggle the full screen mode, press "more" on palettes, open the menus

Expected behaviour: no glitches at all.
Actual behaviour: glitch almost anytime (look the top of the screen).

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/a2516a5d-912a-4e24-b545-52497d555c1a

### What is the latest version of MuseScore Studio where this issue is present?

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.1-242490810, revision: github-musescore-musescore-0b3dd00

### Regression

I was unable to check

### Operating system

Windows 10 Pro

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by bkunda** [comment]
Could you please provide us with a bit more information? 

- Diagnostic files (go to Diagnostic > Save diagnostic files)
- Details about your graphics hardware (GPU)

**Comment by FrancRos31** [comment]
[Diagnostic.zip](https://github.com/user-attachments/files/16945928/Diagnostic.zip)

Here the specs of my GPU
![1](https://github.com/user-attachments/assets/230cb1e3-cc06-4a00-a964-3719df31cc2f)

**Comment by FrancRos31** [comment]
The update to version 4.4.2 didn't change anything.

[diag.zip](https://github.com/user-attachments/files/17090632/diag.zip)

![1](https://github.com/user-attachments/assets/230cb1e3-cc06-4a00-a964-3719df31cc2f)

**Comment by cbjeukendrup** [comment]
On a first investigation, I see nothing relevant in the log files. 
It's most likely a Qt bug, rather than a bug in MuseScore's own code. You could try if it's fixed in the builds from #24644 (see [How to download test builds from pull requests](https://github.com/musescore/MuseScore/wiki/Downloading-and-running-test-builds#downloading-builds-from-pull-requests) for instructions).

**Comment by FrancRos31** [comment]
> On a first investigation, I see nothing relevant in the log files. It's most likely a Qt bug, rather than a bug in MuseScore's own code. You could try if it's fixed in the builds from #24644 (see [How to download test builds from pull requests](https://github.com/musescore/MuseScore/wiki/Downloading-and-running-test-builds#downloading-builds-from-pull-requests) for instructions).

This build doesn't work at all. The problem remains.

**Comment by zacjansheski** [comment]
I can reproduce this, in all versions of 4 (not a recent regression)
I suspect it has something to do with display settings / scaling,  @cbjeukendrup let me know if there is any additional info I can give you

![Screenshot 2024-09-30 140953](https://github.com/user-attachments/assets/dec846d7-dfb7-41a7-8332-71d06645600e)

**Comment by FrancRos31** [comment]
> I can reproduce this, in all versions of 4 (not a recent regression) I suspect it has something to do with display settings / scaling, @cbjeukendrup let me know if there is any additional info I can give you
> 

Do I need to adjust some setting?

**Comment by cbjeukendrup** [comment]
I think the white flash when a dialog is opened has a different cause. In fact, it has been logged here: https://github.com/musescore/MuseScore/issues/23472

**Comment by FrancRos31** [comment]
I see, but don't you think that's a bug, not a feature request?

**Comment by FrancRos31** [comment]
The issue is pretty bad when opening a new score using the shotcut Ctrl + N.

https://github.com/user-attachments/assets/2efd9cde-df18-42b2-b2a3-5f3f298df343

OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.2-242570931, revision: github-musescore-musescore-3130f97

**Comment by FrancRos31** [comment]
Another one to the list, this time in normal mode (OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.3-242971445, revision: github-musescore-musescore-eb6b367).


Look at the glitch when moving between opened View and Add menus and Help and Diagnostic menus.
https://github.com/user-attachments/assets/8c15a955-e854-4ea0-959f-b62ecb3fbb8c

**Comment by FrancRos31** [comment]
Another one, normal and full screen mode (OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.4.4-243461245, revision: github-musescore-musescore-2232670).

https://github.com/user-attachments/assets/3d7239b1-ae58-420a-a2f4-8e2c9e072b03

**Comment by zacjansheski** [comment]
I am no longer able to reproduce this in Nightly, possibly resolved by latest Qt update.  @FrancRos31 please confirm

**Comment by FrancRos31** [comment]
@zacjansheski, the two issues still not fixed are definitely better on my side. Everything else is fixed, though, thank you.

https://github.com/user-attachments/assets/5ee9840b-6680-4b6d-836e-55d2322fbd32

https://github.com/user-attachments/assets/d18b9546-2ff3-4db5-b0fc-e4091bade352

https://github.com/user-attachments/assets/ec5cf9d8-8b1f-4a46-b33d-7e66aaeeaab1

In the video above (0:12), MS is freezing upon closing.

https://github.com/user-attachments/assets/fba5c9c9-585c-45a0-a361-7844a2728a53

**Comment by zacjansheski** [comment]
@FrancRos31 thank you, I think this issue report has gotten too bloated, as it stands this is the issue:

Windows Glitch 
1. Opening and closing full screen
2. Ctrl+N full screen

Could you please open a fresh issue with just those in the video?  (I'm unable to reproduce)
Then close this report.

**Comment by FrancRos31** [comment]
Closing per above comment, remaining glitches moved to #28772.
