### ISSUE TITLE
System Objects: 'Are you sure want to delete instrument?' dialog appears after deleting system marking

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#26621]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

1. Open [orch.zip](https://github.com/user-attachments/files/18886494/orch.zip)
2. Select system marking (Tempo) in the middle
3. Delete it

![Image](https://github.com/user-attachments/assets/3bdc8f4e-9f12-4988-bd90-eec914d36c32)

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/c83efb11-3a72-441f-8e19-7bb1dc99ea23

### What is the latest version of MuseScore Studio where this issue is present?

4.5 Beta 1

### Regression

No.

### Operating system

Windows 10

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by avvvvve** [comment]
This is fixed in the Nightly now (I think via https://github.com/musescore/MuseScore/pull/26588)

**Comment by DmitryArefiev** [comment]
Nope.. It **still occurs** in latest 4.6 nightly:

https://github.com/user-attachments/assets/830a01a3-76e3-4384-bdac-f813ba6468a5

(the important condition to reproduce: the instrument which contains System marking should have some notes)
