### ISSUE TITLE
Windows, Factory Reset, Dark Mode, Open Score, Crash

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#28840]
### Issue type

Crash or freeze

### Description with steps to reproduce

1. On Windows, Factory Reset and restart program
2. In the opening flow, select dark mode
3. Open new score, crash

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/92c88140-d804-48d8-a9e0-61d99dd6c354

### What is the latest version of MuseScore Studio where this issue is present?

OS: Windows 11 Version 24H2 or later, Arch.: x86_64, MuseScore Studio version (64-bit): 4.6.0-251980328, revision: github-musescore-musescore-9b9348f

### Regression

Yes, this works in the latest released version and is broken in the nightly builds

### Operating system

Windows 11

### Additional context

[diagnostic.zip](https://github.com/user-attachments/files/21297077/diagnostic.zip)

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by zacjansheski** [comment]
@cbjeukendrup could you take a look at the logs here?  Maybe it is related to https://github.com/musescore/MuseScore/pull/28785  ?

**Comment by cbjeukendrup** [comment]
We don't have symbols files for nightly builds (only for release builds), so I can't analyse the crash dump. I'll try in the coming days if I can reproduce it myself. 

The textual log file ends abruptly with 
```
2025-07-17T09:21:07.689 | INFO  | 16796           | MuseSamplerWrapper::initSampler | Successfully initialized sampler, sampleRate: 48000, blockSize: 1024
```
This may either be pure coincidence and totally unrelated, or indicate that the crash happens when MuseSampler starts rendering the playback.

**Comment by juli27** [comment]
I can reproduce the crash on a Windows 11 laptop, but not on a Windows 10 machine. It also reproduces with older nightlies which don’t have the theme listener rewrite yet. MuseSampler is *not* installed on the Windows 11 machine.

[diagnosticfiles.zip](https://github.com/user-attachments/files/21328532/diagnosticfiles.zip)

**Comment by cbjeukendrup** [comment]
I'm having trouble reproducing this in my (virtual) Windows 11 machine. So either there are special circumstances that make this happen, or it might already have been fixed.

**Comment by juli27** [comment]
I can still reproduce this crash. I managed to capture a stack trace:
<details>

```
Qt6Qml!std::_Atomic_integral<int,4>::fetch_add+0x9 [C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.39.33519\include\atomic @ 1507]
Qt6Qml!std::_Atomic_integral_facade<int>::fetch_sub+0x9 [C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.39.33519\include\atomic @ 1723]
Qt6Qml!QAtomicOps<int>::deref+0x9 [C:\Users\qt\work\install\include\QtCore\qatomic_cxx11.h @ 266]
Qt6Qml!QBasicAtomicInteger<int>::deref+0x9 [C:\Users\qt\work\install\include\QtCore\qbasicatomic.h @ 48]
Qt6Qml!QQmlRefCounted<QV4::ExecutableCompilationUnit>::release+0x9 [C:\Users\qt\work\qt\qtdeclarative\src\qml\qml\ftw\qqmlrefcount_p.h @ 152]
Qt6Qml!QV4::Heap::JavaScriptFunctionObject::destroy+0x1b [C:\Users\qt\work\qt\qtdeclarative\src\qml\jsruntime\qv4functionobject.cpp @ 75]
Qt6Qml!QV4::Chunk::sweep+0xcb [C:\Users\qt\work\qt\qtdeclarative\src\qml\memory\qv4mm.cpp @ 286]
Qt6Qml!QV4::BlockAllocator::sweep::__l2::<lambda_1>::operator()+0x10 [C:\Users\qt\work\qt\qtdeclarative\src\qml\memory\qv4mm.cpp @ 565]
Qt6Qml!std::partition+0x50 [C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.39.33519\include\algorithm @ 5768]
Qt6Qml!QV4::BlockAllocator::sweep+0x65 [C:\Users\qt\work\qt\qtdeclarative\src\qml\memory\qv4mm.cpp @ 564]
Qt6Qml!QV4::`anonymous namespace'::doSweep+0x2e [C:\Users\qt\work\qt\qtdeclarative\src\qml\memory\qv4mm.cpp @ 879]
Qt6Qml!QV4::executeWithLoggingIfEnabled+0x1c [C:\Users\qt\work\qt\qtdeclarative\src\qml\memory\qv4mm.cpp @ 1523]
Qt6Qml!QV4::GCStateMachine::transition+0x1f6 [C:\Users\qt\work\qt\qtdeclarative\src\qml\memory\qv4mm.cpp @ 1552]
Qt6Qml!QV4::GCStateMachine::step+0x5 [C:\Users\qt\work\qt\qtdeclarative\src\qml\memory\qv4mm_p.h @ 89]
Qt6Qml!QV4::MemoryManager::onEventLoop+0xcc [C:\Users\qt\work\qt\qtdeclarative\src\qml\memory\qv4mm.cpp @ 1113]
Qt6Core!QtPrivate::QSlotObjectBase::call+0x22 [C:\Users\qt\work\qt\qtbase\src\corelib\kernel\qobjectdefs_impl.h @ 461]
Qt6Core!QMetaCallEvent::placeMetaCall+0x3b [C:\Users\qt\work\qt\qtbase\src\corelib\kernel\qobject.cpp @ 629]
Qt6Core!QObject::event+0x182 [C:\Users\qt\work\qt\qtbase\src\corelib\kernel\qobject.cpp @ 1431]
Qt6Widgets!QApplicationPrivate::notify_helper+0x151 [C:\Users\qt\work\qt\qtbase\src\widgets\kernel\qapplication.cpp @ 3305]
Qt6Widgets!QApplication::notify+0x1669 [C:\Users\qt\work\qt\qtbase\src\widgets\kernel\qapplication.cpp @ 3256]
Qt6Core!QCoreApplication::notifyInternal2+0x101 [C:\Users\qt\work\qt\qtbase\src\corelib\kernel\qcoreapplication.cpp @ 1106]
Qt6Core!QCoreApplication::sendEvent+0x10 [C:\Users\qt\work\qt\qtbase\src\corelib\kernel\qcoreapplication.cpp @ 1546]
Qt6Core!QCoreApplicationPrivate::sendPostedEvents+0x202 [C:\Users\qt\work\qt\qtbase\src\corelib\kernel\qcoreapplication.cpp @ 1879]
Qt6Gui!QWindowsGuiEventDispatcher::sendPostedEvents+0xf [C:\Users\qt\work\qt\qtbase\src\gui\platform\windows\qwindowsguieventdispatcher.cpp @ 44]
Qt6Core!QEventDispatcherWin32::processEvents+0x90 [C:\Users\qt\work\qt\qtbase\src\corelib\kernel\qeventdispatcher_win.cpp @ 470]
Qt6Gui!QWindowsGuiEventDispatcher::processEvents+0x19 [C:\Users\qt\work\qt\qtbase\src\gui\platform\windows\qwindowsguieventdispatcher.cpp @ 37]
Qt6Core!QEventLoop::processEvents+0x24 [C:\Users\qt\work\qt\qtbase\src\corelib\kernel\qeventloop.cpp @ 104]
Qt6Core!QEventLoop::exec+0x1c4 [C:\Users\qt\work\qt\qtbase\src\corelib\kernel\qeventloop.cpp @ 185]
Qt6Core!QCoreApplication::exec+0x16a [C:\Users\qt\work\qt\qtbase\src\corelib\kernel\qcoreapplication.cpp @ 1449]
MuseScore4!main+0x697 [D:\dev\MuseScore\src\app\main.cpp @ 217]
MuseScore4!invoke_main+0x22 [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 78]
MuseScore4!__scrt_common_main_seh+0x10c [D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 288]
KERNEL32!BaseThreadInitThunk+0x17
ntdll!RtlUserThreadStart+0x2c
```
</details>

The crash occurs here when `executableCompilationUnit()` returns a nullptr:
https://github.com/qt/qtdeclarative/blob/1e6adc3d5f1f4cbbb77b41911395782dff43cccd/src/qml/jsruntime/qv4functionobject.cpp#L75
So this is either a Qt bug or we free an object which is owned by Qml.
I've also bisected the nightlies:
- good nightly: 162 (4870d00)
- bad nightly: 163 (0466e0c)
commit diff: https://github.com/musescore/MuseScore/compare/4870d00...0466e0c
163 is the nightly where we switched CI to Qt 6.9.1.

Don't really know where to go from here

**Comment by juli27** [comment]
Disabling incremental GC (default since Qt 6.8) by setting the `QV4_GC_TIMELIMIT` environment variable to 0[^1] seems to be a workaround for this crash. (in case no one is able to track down the cause)

[^1]: https://doc.qt.io/qt-6/qtqml-javascript-memory.html#garbage-collection

**Comment by bkunda** [comment]
I too can reproduce this. What's particularly bad is that the app continually crashes for me on score creation, rendering it quite unusable (unless, presumably, I factory reset again and proceed without changing the theme). 

@igorkorsukov in @cbjeukendrup's absence today, are you pls able to have a look at this?

**Comment by igorkorsukov** [comment]
I'll take a look

**Comment by igorkorsukov** [comment]
I can't reproduce the problem 

I think we need to use the found @juli27 (thanks!), set QV4_GC_TIMELIMIT = 0
@juli27 Could you make a PR or is it better me to make it?
