### ISSUE TITLE
Local time signature delete and undo corrupts score

### ISSUE THREAD

**Issue by zacjansheski** [musescore/MuseScore#29789]
### Issue type

File corruption

### Description with steps to reproduce

1. Add local times signature to score
2. Delete/Undo
3. Save, score is corrupt

### Supporting files, videos and screenshots

https://github.com/user-attachments/assets/6d6bbd1a-8ec2-486e-9052-e2bd657a5405

### What is the latest version of MuseScore Studio where this issue is present?

OS: macOS Sequoia (15.6), Arch.: arm64, MuseScore Studio version (64-bit): 4.6.0-252510405, revision: github-musescore-musescore-ca12911

### Regression

No.

### Operating system

MacOS15

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by Reedbeta** [comment]
FWIW, I'm not seeing this issue on latest master, so it may have been fixed.

**Comment by cbjeukendrup** [comment]
It seems that I can still reproduce it, but I was confused for a moment by step 2, "Delete/Undo": I initially read it as "delete or undo", which does not cause trouble, but it should have been "delete the local time sig, and then undo that deletion". Is it possible you had the same confusion @Reedbeta ?

**Comment by Reedbeta** [comment]
Hmm, I don't think I was confused, but I just tried it again and I did reproduce it this time. Not sure what happened the first time I tried it. Sorry for the noise.

**Comment by 0xMashiro** [comment]
I independently reproduced the delete **and then undo** corruption on official main `a64e0d0c8725a89af2b4b9f8e058a75be20c01d3` and opened a candidate fix: #34845 (draft).

The reproduction has local 7/8 in Clarinet measure 2 and local 5/4 in measure 3. Delete the 5/4, undo, and save. The 5/4 object is restored, but the full-score staff map still returns 7/8, and the save integrity check reports incomplete measures. Restoring the complete time-signature segment bypasses the individual-item registration hook.

The new native regression fails on the unmodified baseline; with the candidate, all 16 native time signature tests pass. It covers deletion from either the full score or linked part, undo/redo, integrity validation, and MSCZ save/reopen. Agent-operated Linux desktop recordings also reproduce the corruption warning before the change and successful saving after it.

[Scores, steps, build identity and logs](https://github.com/0xMashiro/MuseScore/blob/e8027265234712f11162b2dda2136a39e972bd38/README.md)

**Before video:**

https://github.com/user-attachments/assets/fa78758e-93af-4b4b-9aa4-185d8bfdba28

**After video:**

https://github.com/user-attachments/assets/d95978f0-2072-46e8-b4c4-9e1170b90783

This supplies a concrete reproduction and candidate for the existing report; it does not claim the issue was previously unreported.
