### ISSUE TITLE
Lyric hyphens in 4.6 not consistently working

### ISSUE THREAD

**Issue by Mikey12045** [musescore/MuseScore#30284]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

When using the hyphen key to separate lyric syllables, hyphens do not always appear, although the cursor moves to the next syllable. Some actions, such as zooming in and out, selecting and deselecting a syllable, or closing and reopening the score, may cause some hyphens to reappear, but they may disappear a few actions later. Completely undependable. 

### Supporting files, videos and screenshots

None available

### In which versions of MuseScore Studio is this issue present?

4.6

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Mac 13.7.7

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by MarcSabatella** [comment]
My guess is you are seeing the effect of the feature where, as per standard practice, hyphens are omitted when space is tight between syllables.  If you prefer extra space be allocated to make room for a hyphen, go to Format / Style / Lyrics and disable the option to "Omit hyphens when space is limited".

If this is not what you are referring to, please ZIP and attach a score that demonstrates the problem, and say which lyric in which measure you are referring to.

**Comment by Mikey12045** [comment]
Screenshot in continuous view, so spacing should not have been an issue. Reverting to 4.5.2 worked correctly, in the same environment. Note particularly the gap between **a** and **way** in mm 19-20. Certainly enough room, there.

I no longer have the original document. I trashed it (and 4.6) and reverted to 4.5.2 to complete the job. Sorry.

![Image](https://github.com/user-attachments/assets/6fd8c6f0-d976-4fdd-9031-68195748d3a6)

**Comment by ghost** [comment]
@Mikey12045 Well if you can supply us with the file, we can open it in 4.6 and experiment.
Was this problem evident in page view as well, or only in continuous view?

**Comment by Mikey12045** [comment]
I've attached the XML, which I created in SmartScore Pro.

I never got as far as Page View. I do my copywork in Continuous, only switching to Page View when the notes and lyrics are in.

[After the Roses Have Faded Away.xml](https://github.com/user-attachments/files/22703674/After.the.Roses.Have.Faded.Away.xml)

**Comment by ghost** [comment]
@miiizen In this file, add an extension line to 'gone.' in b23 to see the issue. Only evident in continuous view.

[After.the.Roses.Have.Faded.Away.mscz.zip](https://github.com/user-attachments/files/22703834/After.the.Roses.Have.Faded.Away.mscz.zip)
(File saved in 4.5.2 so you can open it there to see the difference if useful.)

**Comment by Mikey12045** [comment]
I know that extension line is missing. I just hadn't gotten that far! And I know the problem is not there in 4.5.2.

But in 4.6, the problem only happens in Continuous view, and the hyphens show up in Page View? If that's the case, then can you reclassify my complaint, and set it up to be fixed in Continuous, please?

**Comment by ghost** [comment]
@Mikey12045 My instructions are to the developer who will be working on this. I'm telling him how to easily reproduce the issue.

As you can see, I have retitled this issue to specify that it affects continuous view.

**Comment by Mikey12045** [comment]
And I thank you, sir!

**Comment by Mikey12045** [comment]
Thanks to all of you who worked on this. I'll eagerly await the next stable release!

**Comment by marcdir** [comment]
Mac OS Sonoma 14.8.2.
Just updated to 4.6.4 today and still experiencing hyphen issues, especially while using 1. volta.


With 1. volta, it is impossible to put an hyphen between «Sei» and «gneur». However, the hyphen under 2. volta is working properly :
<img width="527" height="602" alt="Image" src="https://github.com/user-attachments/assets/ed0fee48-f50c-4535-ae63-06e5322fd029" />


If I remove the 1.volta, I can put the hyphen normally, but it breaks the hyphen under 2. volta :
<img width="516" height="533" alt="Image" src="https://github.com/user-attachments/assets/1f2c9dc4-a419-4713-b7e5-0a6d1d731ebf" />


Would you need a video ?

**Comment by MarcSabatella** [comment]
Videos can sometimes be helpful, but much more important is to ZIP and attach the actual score.  Since this is apparently not about continuous view, and the original bug was fixed already, this seems unrelated.  So please open a new issue and attach the score and give precise steps to reproduce the problem there.

**Comment by marcdir** [comment]
https://github.com/musescore/MuseScore/issues/31393

**Comment by Mikey12045** [comment]
I can confirm that this is still a problem in 4.6.6, particularly when using x to move lyrics above the staff.
