### ISSUE TITLE
MSS 4.6.3 crashes when the W11 screen saver kicks in (Audio output via USB connection to monitor)

### ISSUE THREAD

**Issue by psdepsde** [musescore/MuseScore#31213]
### Issue type

Crash or freeze

### Description with steps to reproduce

When the Windows11 (24H2 and 25H2) scree saver kicks in MuseScore Studio 4.6.3 crashes. The message in the log is 
_2025-11-25T11:34:51.299 | ERROR | 30992           | WasapiAudioClient::setStateAndNotify | AUDCLNT_E_DEVICE_INVALIDATED_
It seems to try to reinitialize itself, but it hits the same error and this time it's fatal.
When you start MSS again, it asks if you want to restore the session, which works fine.
All the same, it's a bit annoying.

1. Open a score (doesn't matter what's in it - I used a 14 bar duet when reproducing for this PR)
2. Leave the PC alone until the screensaver starts (5 mins for me)
3. Wait a couple of minutes while MSS tries to recover from the error (takes 60-80 seconds for me)
4. Move the mouse to wake up the PC and observe that MSS is no longer running
5. Inspect the end of MuseScore_251126_164537.log provided in the attached zip

### Supporting files, videos and screenshots

[screensaver_crash.zip](https://github.com/user-attachments/files/23762896/screensaver_crash.zip)

### In which versions of MuseScore Studio is this issue present?

4.6.3 - haven't checked the nightly

### Regression

I was unable to check

### Operating system

Windows11 24H2 and 25H2

### Additional context

W11 screensaver settings:

<img width="837" height="607" alt="Image" src="https://github.com/user-attachments/assets/c613ead4-8375-476d-a7a8-e70b9c78d5d4" />

My screensaver is a black screen.

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by zacjansheski** [comment]
Looks like this is indeed still reproducible https://github.com/musescore/MuseScore/issues/20674

**Comment by cbjeukendrup** [comment]
Might be better in 4.7, because Igor rewrote the WASAPI driver

**Comment by zacjansheski** [comment]
@psdepsde could you please try to reproduce this issue in 4.7 nightly when you are able?

**Comment by cbjeukendrup** [comment]
(i.e. the "master" builds from https://ftp.osuosl.org/pub/musescore-nightlies/windows/4x/nightly/?C=M;O=D)

**Comment by psdepsde** [comment]
Will do.

Sorry my github search didn't turn up the duplicate.

**Comment by psdepsde** [comment]
Yes, it's reproducible with MuseScore-Studio-Nightly-253300326-master-8cf1081-x86_64.paf.exe

Here's the zip file from the test.

Cheers - Peter

[MSS_4.7.0_portable.zip](https://github.com/user-attachments/files/23781897/MSS_4.7.0_portable.zip)

**Comment by psdepsde** [comment]
And reproducible in released 4.6.4 of course

**Comment by DmitryArefiev** [comment]
I **can't reproduce** in 4.6.3, 4.6.5 on my Windows 11 25H2

@psdepsde Do you have some additional audio device on you system (or just internal Realtek)?

Also, can you try the latest nightly please? https://github.com/musescore/MuseScore/actions/runs/20420927064

**Comment by psdepsde** [comment]
Yes, it's still reproducible with ...\MU4_253560334_Win_portable_master\MuseScorePortable\MuseScorePortable.exe on up to date Win 11 25H2, though the log messages are different now. In the uploaded zip file, MuseScore_251223_103840.log ends with:

2025-12-23T10:38:52.309 | ERROR | 27476           | <lambda_1>::operator  | >>>>>>>>>>>>>>>>> [10:38:52.309686] [27476] Failed to get subscription infos: Failed to parse API data.  <<<<<<<<<<<<<<<<<<

2025-12-23T10:42:07.316 | INFO  | main_thread     | <lambda_1>::operator  | Available output devices changed, checking connection...
2025-12-23T10:42:07.324 | INFO  | main_thread     | WasapiAudioDriver::open | try open driver, device: {0.0.0.00000000}.{e4d0ba75-d376-433c-899d-177c595d1568}
2025-12-23T10:43:58.165 | INFO  | main_thread     | <lambda_1>::operator  | Available output devices changed, checking connection...
2025-12-23T10:43:58.180 | INFO  | main_thread     | WasapiAudioDriver::open | try open driver, device: {0.0.0.00000000}.{e4d0ba75-d376-433c-899d-177c595d1568}
2025-12-23T10:48:07.611 | INFO  | main_thread     | <lambda_1>::operator  | Available output devices changed, checking connection...

but the timestamps are a bit odd. The sequence of events was:
10:38 start MuseScorePortable.exe
10:40 stop moving mouse
10:48 screen saver cuts in (not at 10:45 as expected)
10:53 wake up PC by moving mouse
10:54 restart MuseScorePortable.exe to create zip file

Audio output is via USB connection to a Dell U2721DE monitor which feeds audio to a pair of powered speakers.
Audio driver is

<img width="394" height="241" alt="Image" src="https://github.com/user-attachments/assets/8af0b19f-1e71-4317-9cec-825bed5367ee" />

[#31213-2025-12-23.zip](https://github.com/user-attachments/files/24301530/31213-2025-12-23.zip)

**Comment by psdepsde** [comment]
I connected the speakers directly into the headphone socket on the PC and was **unable** to reproduce the problem.  Ditto for the audio out (presumably line out) socket on the back panel.

**Comment by psdepsde** [comment]
FWIW, both of these recablings were done while MSS was running (but not playing) and in both cases it crashed. But IMHO, this is acceptable. Expecting it to keep going while you rearrange its hardware is a bit unreasonable, I think.

**Comment by DmitryArefiev** [comment]
> I connected the speakers directly into the headphone socket on the PC and was **unable** to reproduce the problem. Ditto for the > audio out (presumably line out) socket on the back panel.

Good! This isolates the problem.  

> Audio output is via USB connection to a Dell U2721DE monitor which feeds audio to a pair of powered speakers.

Can you also show what audio output devices you have in System>Sound?

<img width="961" height="764" alt="Image" src="https://github.com/user-attachments/assets/7e1ea3b8-d21c-430b-95a2-57c414ad481f" />

**Comment by psdepsde** [comment]
Hi Dmitry
I'm away from home for a week. I'll do this as soon as I return.
Cheers - Peter

**Comment by psdepsde** [comment]
<img width="545" height="824" alt="Image" src="https://github.com/user-attachments/assets/aeebafd4-19e5-4f0a-81fa-9f772f02c5cf" />

<img width="522" height="732" alt="Image" src="https://github.com/user-attachments/assets/d1c7ba70-e0c6-4186-8e40-72eef0321551" />

**Comment by DmitryArefiev** [comment]
@psdepsde Hi! Can you try again please on latest master? https://github.com/musescore/MuseScore/actions/runs/21018761481
We merged some similar crash fix recently

**Comment by psdepsde** [comment]
Good news - I **can't** reproduce the problem with the above master.  To make sure I was testing properly, I tried the exact same steps with the released 4.6.5, and can still reproduce there. So problem solved IMO. Thanks very much!

**Comment by DmitryArefiev** [comment]
Cool! Thanks for testing!
