### ISSUE TITLE
[MU4 Issue] Crash when uses shortcut CTRL + 6

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7683]
**Describe the bug**
Crash when uses shortcut CTRL + 6

**To Reproduce**

1. Enter note on the score
2. Click on entered note
3. Press CTRL + 6 from the keyboard several times

**Expected behavior**
Sextuplet added

**Screenshots**

![0vmAlNDRaqU](https://user-images.githubusercontent.com/71372310/110196736-957a3200-7e57-11eb-98c0-c677a5863ef5.jpg)

**Desktop (please complete the following information):**
Windows 10

**Comment by shoogle** [comment]
Does the crash occur with the menu option (Add > Tuplets > Sextuplet) as well as via the Ctrl+6 keyboard shortcut?

**Comment by vshalkevich** [comment]
Crash reproduces with all CTRL + 2...9 combinations. 
Also Crash if you click any tuplet (2...9) from the context UI menu

**Comment by vshalkevich** [comment]
Additional wat to reproduce:
1. Create a score
2. Add a note
3. Select created note
4. Click "Tuplet" from Note Input Bar 
5. Click "Triplet"

**Actual result**
Crash

**Comment by qtweng** [comment]
Upon investigation, noticed interesting behavior that anything done through the Add menu bar is done twice. This is somehow causing the app to access invalid addresses.

**Comment by shoogle** [comment]
@qtweng, good observation! I can confirm that *Add > Notes > C* causes 2 notes to appear in the score rather than the one you get by pressing the C shortcut, and similarly for other actions in the Add menu.

**Comment by Eism** [comment]
Fixed twice triggering in #7801 
Other crashes need to be investigated

**Comment by vshalkevich** [comment]
Edited main bug report according to existing bug

**Comment by DmitryArefiev** [comment]
Tested on latest master - **STILL OCCURS**

https://user-images.githubusercontent.com/90187801/143058375-a0cf025b-6e0d-4801-ab78-07191d74fba8.mp4

**Comment by DmitryArefiev** [comment]
The issue doesn't occur in MU3. Adding P1

Other steps to reproduce:
1. Select note
2. Hit Ctr+3 twice

**Comment by Eism** [comment]
May be fixed by #9999
