### ISSUE TITLE
[MU4 Issue] Access Violation on shutdown (Windows)

### ISSUE THREAD

**Issue by wizofaus** [musescore/MuseScore#8154]
**Describe the bug**
Unhandled Access Violation occurs when quitting MuseScore 4 if a score has been opened

notationuiactions.cpp, line 1255
`m_controller->currentNotationInteraction()->scoreConfigChanged().onReceive(this, [this](ScoreConfigType configType)`

**To Reproduce**

1. Build/Run MuseScore4 from VS 2019/Windows 2010
2. Open or create any score
3. Quit

**Expected behavior**
Probably shouldn't crash.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**

**Comment by RomanPudashkin** [comment]
Fixed in https://github.com/musescore/MuseScore/pull/8312

**Comment by wizofaus** [comment]
Nope, it's still happening, though in a different place now - ~UiEngine(), when it deletes theme, which is a static/global QObject-derived entity.
