### ISSUE TITLE
[MU4 Issue] Save Score dialog appears if no changes made in score

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#8415]
**Describe the bug**
Save Score dialog appears if no changes made in score or when score is already has been saved

**To Reproduce**
1. Create a score
2. Make changes in the score
3. Save score manually 
4. Click close MU4 button
OR
1. Open created score (existing in your OS)
2. Click close MU4 button (without making any changes in the score)

**Expected behavior**
Save Score dialog should appear only if there were changes in the score.
If no changes in saved score, save score dialog should not be displayed

**Desktop (please complete the following information):**
Windows, 
Linux
MacOS

**Comment by wizofaus** [comment]
I can't reproduce this - only when creating a new score from template and not changing any defaults (I.e. just clicking "Done" in New Score dialog), but that's a debatable case. But I suspect it might have been happening because of a bug I fixed where clicking on the score caused the undo stack to be modified.

**Comment by Eism** [comment]
The problem is with frequent updates of styles in the inspector
https://github.com/musescore/MuseScore/pull/8346/files#diff-4b77609510d379542ef3fd1e6ba45e35147d0f0b26edc1227dd22cf07a0fcf17L126

If we will merge the solution from #8346, then the problem should be fixed.

**Comment by wizofaus** [comment]
I'd say it's already fixed by another change I made to AbstractInspectorModel::updateStyleValue( ) that's already merged.

**Comment by Eism** [comment]
@vshalkevich please check on the last master

**Comment by macias** [comment]
The bug is still there, OS: openSUSE Leap 15.3, Arch.: x86_64, MuseScore version (64-bit): 4.1.1-232071203, revision: github-musescore-musescore-e4d1ddf.

1. Open score.
2. Make changes
3. Save 
4. Quit

You will see the prompt stating there are unsaved changes and what to do next.

Should I open separate ticket for this, or can we reopen this one?

**Comment by cbjeukendrup** [comment]
In this case I'd create a fresh new issue. Also, it might be useful to test first whether it also still happens in the 4.2 nightly builds (see https://musescore.org/en/nightly-builds). Probably it does, but you never know.

**Comment by macias** [comment]
Thank you for pointing out NB, it is fixed there :-)
