### ISSUE TITLE
Customise toolbar menu is missing icons

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#8682]
A number of icons are missing from the wrench icon menu in the toolbar.

<img width="1145" alt="Screenshot 2021-07-21 at 22 02 32" src="https://user-images.githubusercontent.com/86290556/126485569-7590b783-61ec-4448-a9d7-524936098fef.png">

The missing icons appear to be all those that are **unchecked** in the Figma file/UX document.
(I.e. this image below):

<img width="292" alt="PEDAL  MARKING_CUSTOM+SHOW_MORE" src="https://user-images.githubusercontent.com/86290556/126484467-f6562aa7-a465-48a0-a87f-1bf8fe762b3b.png">

In other words, all unchecked items in the above image are currently **missing** from the wrench icon menu in the toolbar.

**Expected behavior**
All menu items above should be visible in the settings popup, accessible by the wrench icon in the toolbar 

**To Reproduce**
<img width="1719" alt="Frame 1" src="https://user-images.githubusercontent.com/86290556/126485024-32a6b592-a181-4bbc-bcb5-84c6a4bb5ac9.png">

This is a critical issue because most (if not all) of these affordances rely on being accessible from this menu in order to be usable. 

Macbook Air M1 MacOS 11.4
Reproduced in Windows 10 (via Parallels)

**Comment by RomanPudashkin** [comment]
fixed in https://github.com/musescore/MuseScore/pull/8759

**Comment by bkunda** [comment]
Checked latest nightly build (10 Sep) and thees icons are still missing.

**Comment by vshalkevich** [comment]
Cant reproduce for Windows 10 (on the left side missed icons from this issue, on the right side icons that I see on MU4 for Windows 10)
![2021-09-10 12_15_34-Window](https://user-images.githubusercontent.com/71372310/132831155-ed33cf7e-f6ab-4ed5-8de0-62f96b33f38e.jpg)

**Comment by DmitryArefiev** [comment]
@bkunda Strange I **can't** reproduce it on my side as well (Mac10.15.6). Can you try again please? Maybe with a new score..

![master_mac10 15 6](https://user-images.githubusercontent.com/90187801/132834816-3d7ac788-5a86-46b8-9993-72c4be7654c5.png)

**Comment by bkunda** [comment]
Strange indeed. To be absolutely sure, I removed my copy of the latest nightly from my system and re-downloaded it. This is the one I have:
<img width="395" alt="Screenshot 2021-09-10 at 19 57 14" src="https://user-images.githubusercontent.com/86290556/132836514-ba532769-fcac-46f0-ae85-3e9315a71b0d.png">

I created a new score, and this is the customise toolbar menu I see when I click this icon: 
<img width="1144" alt="Screenshot 2021-09-10 at 19 58 13" src="https://user-images.githubusercontent.com/86290556/132836698-bdb38895-6eb0-4847-847c-53d6b885fdb4.png">

<img width="1145" alt="Screenshot 2021-09-10 at 19 54 52" src="https://user-images.githubusercontent.com/86290556/132836716-9ff5e786-9a70-420c-b9e1-440b0bebbef3.png">
<img width="296" alt="Screenshot 2021-09-10 at 19 54 59" src="https://user-images.githubusercontent.com/86290556/132836729-25bb26b7-455c-4611-bcec-342a4390f66f.png">

As you can see, the extra icons are still missing.

**Comment by bkunda** [comment]
Update: I can see all the icons when I open the nightly on a different machine (I also have a slightly older intel based MacBook Air at home). The issue may have something to do with a) how these builds are opening on my machine, and/or b) the M1 chip??

**Comment by DmitryArefiev** [comment]
Could be M1.. But I don't have M1 machine on my side yet to check.

Can you Reset Preferences and try again please?

1. Go to Edit>Preferences>Reset Preferences at the bottom (click OK)
2. Restart MU4
3. Create new score

**Comment by bkunda** [comment]
Bingo. That did it 🙏🏻. Many thanks!

**Comment by DmitryArefiev** [comment]
Oh cool!

**Comment by cbjeukendrup** [comment]
Would that mean that if we ever add a new item to the toolbar in an update, users who have customized their toolbar won't see it nor have the possibility to make it visible? That also seems an issue to me...

**Comment by bkunda** [comment]
@cbjeukendrup I have mentioned this to our dev team. The "reset preferences" fix has since also fixed another (seemingly non-preference-related) issue.
