### ISSUE TITLE
[Inspector] When manually altering the height of a spacers, the values in the inspector do not refresh

### ISSUE THREAD

**Issue by Tantacrul** [musescore/MuseScore#9284]
**Describe the bug**
See video. The 'Height' value in the inspector does not update with changed values until you reselect it.

https://user-images.githubusercontent.com/21022311/134780700-87404ba8-df88-4883-b824-5e91e771b3c8.mov

**Comment by wizofaus** [comment]
That was fixed in my PR too, there are quite a lot of cases where adjusting things on the score didn't update the inspector.

**Comment by Howard-C** [comment]
@wizofaus May I ask what PR?

**Comment by bkunda** [comment]
This issue persists.
The video above shows a different issue. Please see this one for a demo of the problem:

https://user-images.githubusercontent.com/86290556/143033499-024ace6e-a5a7-4041-aa4a-c063fa4d8fc8.mp4

**Comment by HemantAntony** [comment]
@bkunda The first issue you mentioned was already fixed. I fixed the second one (#11070)
