### ISSUE TITLE
[MU4 Issue] VST instrument doesn't have a sound when clicking virtual keyboard (KONTAKT Player only)

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#9419]
**To Reproduce**
1. Invoke VSTi from Mixer
2. Click some keys on VSTi virtual keyboard - you should hear a sample sound

In MU4:

https://user-images.githubusercontent.com/90187801/136812637-02bf8c61-7d7b-4b47-bcc9-37972398293c.mp4

How it works in Sibelius:

https://user-images.githubusercontent.com/90187801/136812706-4f7c7d25-dc41-40bb-b676-60752a0edd6c.mp4

**Desktop (please complete the following information):**
Win10/Mac11
(didn't tried on Linux)

**Comment by Tantacrul** [comment]
Fixed in most recent versions of MS4

**Comment by DmitryArefiev** [comment]
@Tantacrul It still doesn't work well with Kontakt Player on my side..

https://user-images.githubusercontent.com/90187801/166722241-44c7b7cf-14c6-4b79-a7fd-a727db56de80.mp4

**Comment by Tantacrul** [comment]
OK, got it. Thanks!

**Comment by Tantacrul** [comment]
If this requires significant work to fix, we can potentially move it to post beta. However, it is quite bad if a user can't preview sounds using their keyboard and Kontakt is almost certainly going to be one of the top three VSTs used.

**Comment by DmitryArefiev** [comment]
Tested in **latest master** on Win10, Mac12 - **Looks fine now. FIXED**

Closing
