### ISSUE TITLE
[MU4 Issue] Settings in Styles dialog override changes to individual text objects made in properties panel

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#9837]
**Describe the bug**
There are two parts to this problem (probably related, I suspect).
1. Changes made to individual text objects from the **Properties** panel are reversed by selecting practically any setting within the **Styles** dialog (even those that have nothing to do with text objects)
2. Changes made to text styles within the **Styles** dialog are overriding changes made to individual text objects on an instance-by-instance basis from within the **Properties** panel.

https://user-images.githubusercontent.com/86290556/143011752-041cb0bd-31ca-45d1-8dcc-f8a4a2494feb.mp4

**Expected behavior**
1. Changing a setting in the **Styles** dialog should not affect the appearance of text objects that have been individually styled in the **Properties** panel.
2. Changing the style of a particular text object class (e.g. "Title" or "Lyrics") should not override instance-by-instance changes made to those text objects from within the **Properties** panel.

**Desktop (please complete the following information):**
 - MacOS 11.6
 - Windows 11

**Comment by DmitryArefiev** [comment]
Hello @bkunda can you try this on Mac/Win on your side please? (builds from #9932)

I'll check it on Linux

**Comment by bkunda** [comment]
Testing now

**Comment by bkunda** [comment]
Tested on MacOS and Windows. Both problems have been fixed 👌🏻

**Comment by DmitryArefiev** [comment]
@bkunda Thank you for testing! I've tried on Linux. And both issues are seems to be fixed, but not in all cases..

@RomanPudashkin  **1st issue** still occurs for Instrument names when changing default font only for Title text. Please see the video:

https://user-images.githubusercontent.com/90187801/145409267-370cddbb-1be3-4056-bf43-7504863c62f9.mp4

Do you want a separate issue or just reopen the current ? (if it's the same problem)

**Comment by bkunda** [comment]
Hey @DmitryArefiev, good spot! I can confirm this issue is also on Windows and MacOS.

**Comment by DmitryArefiev** [comment]
@bkunda Thanks! Raised that separately #10033
Roman said this is more complex issue (changing Instrument name text properties from Properties individually for each element) and requires a a lot of refactoring work.
